// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounting.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO app.accounting_periods (id, year, month, status)
VALUES ($1::uuid, $2::int, $3::int, COALESCE($4::text, 'open'))
RETURNING id, year, month, status
`

type CreatePeriodParams struct {
	ID     string
	Year   int32
	Month  int32
	Status *string
}

// Mở một kỳ kế toán mới (status 'open'). UNIQUE(year,month) chống trùng. id sinh
// app-side. Dùng cho seed/khởi tạo kỳ (P0 chưa expose REST quản lý kỳ).
func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (AppAccountingPeriod, error) {
	row := q.db.QueryRow(ctx, createPeriod,
		arg.ID,
		arg.Year,
		arg.Month,
		arg.Status,
	)
	var i AppAccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Status,
	)
	return i, err
}

const getChartAccount = `-- name: GetChartAccount :one

SELECT account_code, allow_posting, balance_type, type
FROM public.chart_of_accounts
WHERE account_code = $1::text
  AND deleted_at IS NULL
`

type GetChartAccountRow struct {
	AccountCode  string
	AllowPosting bool
	BalanceType  string
	Type         string
}

// Accounting (P0 — sổ kế toán nền). GHI object MỚI ở schema app
// (journal_entries/_lines/accounting_periods) + ĐỌC public.chart_of_accounts
// (strangler, ADR 0001). Tiền debit/credit là NUMERIC(20,0) → common/money ở repo
// (KHÔNG float). PK uuid sinh app-side (common/id v7) và truyền vào INSERT — ổn
// định, time-ordered, không phụ thuộc pgcrypto trên prod. Post bút toán chạy
// TRONG tx do caller truyền (gộp atomic với nghiệp vụ orders/finance): service
// insert entry rồi insert từng line; trigger DEFERRABLE cân Σ lúc commit.
// Đọc một tài khoản trong cây TK theo account_code (chưa soft-delete). Trả
// allow_posting/balance_type/type để service gate hạch toán (chỉ post vào TK
// allow_posting = true). Không thấy → sqlc trả pgx.ErrNoRows (repo map NotFound).
func (q *Queries) GetChartAccount(ctx context.Context, accountCode string) (GetChartAccountRow, error) {
	row := q.db.QueryRow(ctx, getChartAccount, accountCode)
	var i GetChartAccountRow
	err := row.Scan(
		&i.AccountCode,
		&i.AllowPosting,
		&i.BalanceType,
		&i.Type,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, book, entry_date, period_id, source_type, source_id, memo, created_at
FROM app.journal_entries
WHERE id = $1::uuid
`

// Một bút toán theo id (cho HTTP đọc /v1/accounting/entries/{id}).
func (q *Queries) GetEntry(ctx context.Context, id string) (AppJournalEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i AppJournalEntry
	err := row.Scan(
		&i.ID,
		&i.Book,
		&i.EntryDate,
		&i.PeriodID,
		&i.SourceType,
		&i.SourceID,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenPeriodByDate = `-- name: GetOpenPeriodByDate :one
SELECT id, year, month, status
FROM app.accounting_periods
WHERE year = $1::int
  AND month = $2::int
  AND status = 'open'
`

type GetOpenPeriodByDateParams struct {
	Year  int32
	Month int32
}

// Tìm kỳ kế toán chứa entry_date (theo year/month của ngày) VÀ đang 'open'. Dùng
// gate: chỉ post vào kỳ mở. Không có kỳ (chưa mở) hoặc kỳ đã 'closed' → ErrNoRows
// (service phân biệt "không có kỳ mở" = Conflict kỳ khoá).
func (q *Queries) GetOpenPeriodByDate(ctx context.Context, arg GetOpenPeriodByDateParams) (AppAccountingPeriod, error) {
	row := q.db.QueryRow(ctx, getOpenPeriodByDate, arg.Year, arg.Month)
	var i AppAccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Status,
	)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO app.journal_entries (id, book, entry_date, period_id, source_type, source_id, memo)
VALUES ($1::uuid, $2::text, $3::date, $4::uuid,
        $5::text, $6::text, $7::text)
RETURNING id
`

type InsertJournalEntryParams struct {
	ID         string
	Book       string
	EntryDate  pgtype.Date
	PeriodID   string
	SourceType string
	SourceID   string
	Memo       string
}

// Ghi một bút toán (header). book ∈ {INTERNAL,TAX}; period_id là kỳ đang mở (đã
// gate ở service). id sinh app-side. RETURNING id để service insert lines tiếp.
func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (string, error) {
	row := q.db.QueryRow(ctx, insertJournalEntry,
		arg.ID,
		arg.Book,
		arg.EntryDate,
		arg.PeriodID,
		arg.SourceType,
		arg.SourceID,
		arg.Memo,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertJournalEntryLine = `-- name: InsertJournalEntryLine :exec
INSERT INTO app.journal_entry_lines (id, entry_id, line_no, account_code, debit, credit)
VALUES ($1::uuid, $2::uuid, $3::int, $4::text,
        $5::numeric, $6::numeric)
`

type InsertJournalEntryLineParams struct {
	ID          string
	EntryID     string
	LineNo      int32
	AccountCode string
	Debit       pgtype.Numeric
	Credit      pgtype.Numeric
}

// Ghi một dòng bút toán. Mỗi dòng đúng MỘT vế > 0 (CHECK ở DB); Σdebit=Σcredit
// kiểm bởi constraint trigger DEFERRABLE lúc commit. id sinh app-side.
func (q *Queries) InsertJournalEntryLine(ctx context.Context, arg InsertJournalEntryLineParams) error {
	_, err := q.db.Exec(ctx, insertJournalEntryLine,
		arg.ID,
		arg.EntryID,
		arg.LineNo,
		arg.AccountCode,
		arg.Debit,
		arg.Credit,
	)
	return err
}

const listEntries = `-- name: ListEntries :many
SELECT id, book, entry_date, period_id, source_type, source_id, memo, created_at
FROM app.journal_entries
WHERE (
        $1::timestamptz IS NULL
        OR created_at < $1::timestamptz
        OR (created_at = $1::timestamptz
            AND id < $2::uuid)
      )
  AND ($3::text IS NULL OR book = $3::text)
  AND ($4::uuid IS NULL OR period_id = $4::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListEntriesParams struct {
	AfterCreatedAt pgtype.Timestamptz
	AfterID        *string
	Book           *string
	PeriodID       *string
	RowLimit       int32
}

// Danh sách bút toán, keyset theo (created_at DESC, id DESC): trang kế lấy entry
// "cũ hơn" mốc cursor. @after_created_at NULL = trang đầu (từ mới nhất). Lọc
// optional book và period_id.
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]AppJournalEntry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.Book,
		arg.PeriodID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppJournalEntry
	for rows.Next() {
		var i AppJournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Book,
			&i.EntryDate,
			&i.PeriodID,
			&i.SourceType,
			&i.SourceID,
			&i.Memo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryLines = `-- name: ListEntryLines :many
SELECT id, entry_id, line_no, account_code, debit, credit
FROM app.journal_entry_lines
WHERE entry_id = $1::uuid
ORDER BY line_no ASC, id ASC
`

// Các dòng của một bút toán, thứ tự theo line_no (ổn định).
func (q *Queries) ListEntryLines(ctx context.Context, entryID string) ([]AppJournalEntryLine, error) {
	rows, err := q.db.Query(ctx, listEntryLines, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppJournalEntryLine
	for rows.Next() {
		var i AppJournalEntryLine
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.LineNo,
			&i.AccountCode,
			&i.Debit,
			&i.Credit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
