// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByID = `-- name: GetProductByID :one
SELECT
    id, name, sku, barcode, status,
    category_id, manufacturer_id, category_name, manufacturer_name,
    invoice_price, actual_cost,
    wholesale_unit, retail_unit, conversion_factor,
    product_images, created_at, updated_at
FROM public.products
WHERE id = $1 AND deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID               int64
	Name             string
	Sku              *string
	Barcode          *string
	Status           string
	CategoryID       *int64
	ManufacturerID   *int64
	CategoryName     *string
	ManufacturerName *string
	InvoicePrice     pgtype.Numeric
	ActualCost       pgtype.Numeric
	WholesaleUnit    *string
	RetailUnit       *string
	ConversionFactor *int32
	ProductImages    []string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Status,
		&i.CategoryID,
		&i.ManufacturerID,
		&i.CategoryName,
		&i.ManufacturerName,
		&i.InvoicePrice,
		&i.ActualCost,
		&i.WholesaleUnit,
		&i.RetailUnit,
		&i.ConversionFactor,
		&i.ProductImages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, parent_id, status
FROM public.categories
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
ORDER BY name ASC, id ASC
`

type ListCategoriesRow struct {
	ID       int64
	Name     string
	Slug     string
	ParentID *int64
	Status   string
}

func (q *Queries) ListCategories(ctx context.Context, status *string) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManufacturers = `-- name: ListManufacturers :many
SELECT id, name, slug, country, logo_url, status
FROM public.manufacturers
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
ORDER BY name ASC, id ASC
`

type ListManufacturersRow struct {
	ID      int64
	Name    string
	Slug    string
	Country *string
	LogoUrl *string
	Status  *string
}

func (q *Queries) ListManufacturers(ctx context.Context, status *string) ([]ListManufacturersRow, error) {
	rows, err := q.db.Query(ctx, listManufacturers, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManufacturersRow
	for rows.Next() {
		var i ListManufacturersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Country,
			&i.LogoUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductUnits = `-- name: ListProductUnits :many
SELECT
    id, product_id, unit_name, conversion_rate, barcode,
    is_base, is_direct_sale, price_cost, price_sell, unit_type, price
FROM public.product_units
WHERE product_id = $1 AND deleted_at IS NULL
ORDER BY is_base DESC, conversion_rate ASC, id ASC
`

type ListProductUnitsRow struct {
	ID             int64
	ProductID      *int64
	UnitName       string
	ConversionRate *int32
	Barcode        *string
	IsBase         *bool
	IsDirectSale   *bool
	PriceCost      pgtype.Numeric
	PriceSell      pgtype.Numeric
	UnitType       *string
	Price          pgtype.Numeric
}

// Đơn vị tính đa cấp của 1 product (Hộp/Vỉ/Viên). Sắp base trước rồi theo rate.
func (q *Queries) ListProductUnits(ctx context.Context, productID *int64) ([]ListProductUnitsRow, error) {
	rows, err := q.db.Query(ctx, listProductUnits, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductUnitsRow
	for rows.Next() {
		var i ListProductUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UnitName,
			&i.ConversionRate,
			&i.Barcode,
			&i.IsBase,
			&i.IsDirectSale,
			&i.PriceCost,
			&i.PriceSell,
			&i.UnitType,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many

SELECT
    id, name, sku, barcode, status,
    category_id, manufacturer_id, category_name, manufacturer_name,
    invoice_price, actual_cost,
    wholesale_unit, retail_unit, conversion_factor,
    product_images, created_at, updated_at
FROM public.products
WHERE deleted_at IS NULL
  AND id > $1::bigint
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::bigint IS NULL OR category_id = $3::bigint)
  AND (
        $4::text IS NULL
        OR name ILIKE '%' || $4::text || '%'
        OR sku ILIKE '%' || $4::text || '%'
      )
ORDER BY id ASC
LIMIT $5::int
`

type ListProductsParams struct {
	AfterID    int64
	Status     *string
	CategoryID *int64
	Q          *string
	RowLimit   int32
}

type ListProductsRow struct {
	ID               int64
	Name             string
	Sku              *string
	Barcode          *string
	Status           string
	CategoryID       *int64
	ManufacturerID   *int64
	CategoryName     *string
	ManufacturerName *string
	InvoicePrice     pgtype.Numeric
	ActualCost       pgtype.Numeric
	WholesaleUnit    *string
	RetailUnit       *string
	ConversionFactor *int32
	ProductImages    []string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Catalog (read-mostly, ADR 0001): ĐỌC bảng public.* kế thừa. Mọi query lọc
// deleted_at IS NULL (soft-delete). Tiền (invoice_price/actual_cost/price*) là
// numeric → map sang common/money ở repo, KHÔNG dùng float. KHÔNG select cột
// fts (tsvector) — chỉ dùng nó để filter, không scan ra Go.
// Keyset pagination theo id ASC: chỉ lấy id > after_id. after_id = 0 cho trang
// đầu (id bigint luôn > 0). Lấy LIMIT phần tử; app quyết next-cursor. Filter
// optional category_id + q (ILIKE name/sku). status mặc định lọc ở app qua @status.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.AfterID,
		arg.Status,
		arg.CategoryID,
		arg.Q,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.Status,
			&i.CategoryID,
			&i.ManufacturerID,
			&i.CategoryName,
			&i.ManufacturerName,
			&i.InvoicePrice,
			&i.ActualCost,
			&i.WholesaleUnit,
			&i.RetailUnit,
			&i.ConversionFactor,
			&i.ProductImages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
