// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT
    c.id,
    c.customer_code,
    c.name,
    c.customer_type,
    c.phone,
    c.email,
    c.address,
    c.status,
    c.b2b_metadata,
    c.current_debt,
    c.created_at,
    c.updated_at,
    COALESCE((
        SELECT SUM(o.final_amount)
        FROM public.orders o
        WHERE o.customer_id = c.id
          AND o.deleted_at IS NULL
          AND o.payment_status <> 'paid'
    ), 0)::numeric AS live_debt
FROM public.customers c
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCustomerByIDRow struct {
	ID           int64
	CustomerCode *string
	Name         string
	CustomerType string
	Phone        *string
	Email        *string
	Address      *string
	Status       string
	B2bMetadata  []byte
	CurrentDebt  pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	LiveDebt     pgtype.Numeric
}

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (GetCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerCode,
		&i.Name,
		&i.CustomerType,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Status,
		&i.B2bMetadata,
		&i.CurrentDebt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LiveDebt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many

SELECT
    c.id,
    c.customer_code,
    c.name,
    c.customer_type,
    c.phone,
    c.email,
    c.address,
    c.status,
    c.b2b_metadata,
    c.current_debt,
    c.created_at,
    c.updated_at,
    COALESCE((
        SELECT SUM(o.final_amount)
        FROM public.orders o
        WHERE o.customer_id = c.id
          AND o.deleted_at IS NULL
          AND o.payment_status <> 'paid'
    ), 0)::numeric AS live_debt
FROM public.customers c
WHERE c.deleted_at IS NULL
  AND c.id > $1::bigint
  AND ($2::text IS NULL OR c.customer_type = $2::text)
  AND ($3::text IS NULL OR c.status = $3::text)
  AND (
        $4::text IS NULL
        OR c.name ILIKE '%' || $4::text || '%'
        OR c.phone ILIKE '%' || $4::text || '%'
        OR c.customer_code ILIKE '%' || $4::text || '%'
        OR (c.b2b_metadata ->> 'tax_code') ILIKE '%' || $4::text || '%'
      )
ORDER BY c.id ASC
LIMIT $5::int
`

type ListCustomersParams struct {
	AfterID      int64
	CustomerType *string
	Status       *string
	Q            *string
	RowLimit     int32
}

type ListCustomersRow struct {
	ID           int64
	CustomerCode *string
	Name         string
	CustomerType string
	Phone        *string
	Email        *string
	Address      *string
	Status       string
	B2bMetadata  []byte
	CurrentDebt  pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	LiveDebt     pgtype.Numeric
}

// Customers (read-mostly, ADR 0001): ĐỌC bảng public.* kế thừa. Mọi query lọc
// deleted_at IS NULL (soft-delete). Tiền (current_debt) là numeric → map sang
// common/money ở repo, KHÔNG dùng float.
//
// Công nợ LIVE = tổng final_amount các đơn CHƯA tất toán (payment_status <>
// 'paid'), tính từ public.orders, loại đơn soft-deleted. Đây là nguồn ưu tiên so
// với cột tĩnh customers.current_debt (stale). CAVEAT: không trừ được phần đã trả
// của đơn 'partial' vì orders KHÔNG có paid_amount (ghost-debt) — chỉ trình bày.
// B2B (tax_code/debt_limit/payment_term) nằm trong b2b_metadata jsonb → trả raw
// jsonb, repo parse (KHÔNG suy diễn ở SQL).
// Keyset pagination theo id ASC: chỉ lấy id > after_id (after_id = 0 cho trang
// đầu; id bigint luôn > 0). Lọc optional customer_type ('B2B'/'B2C'), status, và
// q (ILIKE name/phone/customer_code + b2b_metadata->>tax_code).
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.AfterID,
		arg.CustomerType,
		arg.Status,
		arg.Q,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerCode,
			&i.Name,
			&i.CustomerType,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Status,
			&i.B2bMetadata,
			&i.CurrentDebt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LiveDebt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
