// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPaymentReceipt = `-- name: ConfirmPaymentReceipt :execrows
UPDATE public.finance_transactions
SET status = 'completed', updated_at = now()
WHERE id = $1::bigint
  AND status = 'pending'
  AND lower(flow) = 'in'
  AND deleted_at IS NULL
`

// Thủ quỹ "Xác nhận đã thu" (thanh toán 2 bước, spec mục 55): chuyển phiếu THU từ
// 'pending' (đã thu từ khách, chưa vào quỹ) → 'completed' (vào quỹ). Trigger prod
// cộng fund_accounts.balance MỘT LẦN tại bước này. CHỈ tác động phiếu đang 'pending'
// (idempotent: gọi lại trên phiếu đã 'completed' → 0 dòng, KHÔNG cộng đôi). flow='in'.
func (q *Queries) ConfirmPaymentReceipt(ctx context.Context, paymentID int64) (int64, error) {
	result, err := q.db.Exec(ctx, confirmPaymentReceipt, paymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAlivePaymentByBankRef = `-- name: FindAlivePaymentByBankRef :one
SELECT
    id, code, transaction_date, flow, business_type, amount, fund_account_id,
    ref_type, ref_id, description, status, bank_reference_id, book_type,
    created_by, created_at
FROM public.finance_transactions
WHERE bank_reference_id = $1::text
  AND deleted_at IS NULL
`

type FindAlivePaymentByBankRefRow struct {
	ID              int64
	Code            string
	TransactionDate pgtype.Timestamptz
	Flow            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         *string
	RefID           *string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
	CreatedAt       pgtype.Timestamptz
}

// Tìm phiếu còn sống theo bank_reference_id — để dedup phiếu thu tự động (webhook).
// Không thấy → ErrNoRows (chưa có, được phép insert).
func (q *Queries) FindAlivePaymentByBankRef(ctx context.Context, bankReferenceID string) (FindAlivePaymentByBankRefRow, error) {
	row := q.db.QueryRow(ctx, findAlivePaymentByBankRef, bankReferenceID)
	var i FindAlivePaymentByBankRefRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TransactionDate,
		&i.Flow,
		&i.BusinessType,
		&i.Amount,
		&i.FundAccountID,
		&i.RefType,
		&i.RefID,
		&i.Description,
		&i.Status,
		&i.BankReferenceID,
		&i.BookType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const findAlivePaymentByCode = `-- name: FindAlivePaymentByCode :one

SELECT
    id, code, transaction_date, flow, business_type, amount, fund_account_id,
    ref_type, ref_id, description, status, bank_reference_id, book_type,
    created_by, created_at
FROM public.finance_transactions
WHERE code = $1::text
  AND deleted_at IS NULL
`

type FindAlivePaymentByCodeRow struct {
	ID              int64
	Code            string
	TransactionDate pgtype.Timestamptz
	Flow            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         *string
	RefID           *string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
	CreatedAt       pgtype.Timestamptz
}

// Finance (P3 — ĐƯỜNG GHI phiếu thu + ĐỌC phiếu của đơn, ADR 0001 strangler):
// GHI/ĐỌC bảng public.finance_transactions kế thừa Supabase. amount = NUMERIC →
// common/money ở repo, KHÔNG float. Liên kết đơn↔phiếu thu qua
// (ref_type='order' AND ref_id = orders.code) — ref_id là TEXT (mã đơn), KHÔNG uuid.
//
// ⚠️ SỐ DƯ QUỸ: PROD có trigger on_finance_transaction_change tự cộng
// fund_accounts.balance khi phiếu sang status='completed'. Vì vậy KHÔNG có query
// nào UPDATE fund_accounts.balance ở đây — tránh double-count. Go chỉ INSERT phiếu
// 'completed', trigger lo số dư.
//
// IDEMPOTENCY: chống ghi phiếu thu TRÙNG (cộng tiền 2 lần):
//   - Phiếu webhook: dedup theo bank_reference_id (FindAlivePaymentByBankRef).
//   - Phiếu thủ công: dedup theo code idempotent sinh từ idem key
//     (FindAlivePaymentByCode). Unique partial index (deleted_at IS NULL) ở DB
//     chặn race (insert lần 2 → unique violation → app re-SELECT trả phiếu cũ).
//
// Tìm phiếu còn sống (chưa xoá mềm) theo code — để dedup phiếu thủ công idempotent.
// Không thấy → ErrNoRows (chưa có, được phép insert).
func (q *Queries) FindAlivePaymentByCode(ctx context.Context, code string) (FindAlivePaymentByCodeRow, error) {
	row := q.db.QueryRow(ctx, findAlivePaymentByCode, code)
	var i FindAlivePaymentByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TransactionDate,
		&i.Flow,
		&i.BusinessType,
		&i.Amount,
		&i.FundAccountID,
		&i.RefType,
		&i.RefID,
		&i.Description,
		&i.Status,
		&i.BankReferenceID,
		&i.BookType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertPaymentIn = `-- name: InsertPaymentIn :one
INSERT INTO public.finance_transactions (
    code, transaction_date, flow, business_type, amount, fund_account_id,
    ref_type, ref_id, description, status, bank_reference_id, book_type, created_by
) VALUES (
    $1::text, now(), 'in', $2::text, $3::numeric,
    $4::bigint, $5::text, $6::text,
    $7::text, $8::text,
    $9::text, $10::text,
    $11::uuid
)
RETURNING
    id, code, transaction_date, flow, business_type, amount, fund_account_id,
    ref_type, ref_id, description, status, bank_reference_id, book_type,
    created_by, created_at
`

type InsertPaymentInParams struct {
	Code            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         string
	RefID           string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
}

type InsertPaymentInRow struct {
	ID              int64
	Code            string
	TransactionDate pgtype.Timestamptz
	Flow            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         *string
	RefID           *string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
	CreatedAt       pgtype.Timestamptz
}

// Ghi MỘT phiếu THU (flow='in') vào public.finance_transactions. id do DB sinh
// (IDENTITY) → KHÔNG truyền id. status truyền 'completed' (tiền đã thực vào quỹ) →
// trigger prod tự cộng fund_accounts.balance MỘT LẦN (Go KHÔNG tự cộng). bank_ref
// NULL cho phiếu thủ công. RETURNING toàn bộ cột để map về domain.Payment.
func (q *Queries) InsertPaymentIn(ctx context.Context, arg InsertPaymentInParams) (InsertPaymentInRow, error) {
	row := q.db.QueryRow(ctx, insertPaymentIn,
		arg.Code,
		arg.BusinessType,
		arg.Amount,
		arg.FundAccountID,
		arg.RefType,
		arg.RefID,
		arg.Description,
		arg.Status,
		arg.BankReferenceID,
		arg.BookType,
		arg.CreatedBy,
	)
	var i InsertPaymentInRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TransactionDate,
		&i.Flow,
		&i.BusinessType,
		&i.Amount,
		&i.FundAccountID,
		&i.RefType,
		&i.RefID,
		&i.Description,
		&i.Status,
		&i.BankReferenceID,
		&i.BookType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertPaymentOut = `-- name: InsertPaymentOut :one
INSERT INTO public.finance_transactions (
    code, transaction_date, flow, business_type, amount, fund_account_id,
    ref_type, ref_id, description, status, bank_reference_id, book_type, created_by
) VALUES (
    $1::text, now(), 'out', $2::text, $3::numeric,
    $4::bigint, $5::text, $6::text,
    $7::text, $8::text,
    $9::text, $10::text,
    $11::uuid
)
RETURNING
    id, code, transaction_date, flow, business_type, amount, fund_account_id,
    ref_type, ref_id, description, status, bank_reference_id, book_type,
    created_by, created_at
`

type InsertPaymentOutParams struct {
	Code            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         string
	RefID           string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
}

type InsertPaymentOutRow struct {
	ID              int64
	Code            string
	TransactionDate pgtype.Timestamptz
	Flow            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         *string
	RefID           *string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
	CreatedAt       pgtype.Timestamptz
}

// Ghi MỘT phiếu CHI (flow='out') vào public.finance_transactions — trả NCC mua hàng
// (mục 54), đối xứng InsertPaymentIn. id do DB sinh (IDENTITY). status 'completed' =
// đã chi khỏi quỹ → trigger prod TRỪ fund_accounts.balance MỘT LẦN (Go KHÔNG tự trừ).
// bank_ref NULL cho phiếu thủ công. RETURNING toàn bộ cột để map về domain.Payment.
func (q *Queries) InsertPaymentOut(ctx context.Context, arg InsertPaymentOutParams) (InsertPaymentOutRow, error) {
	row := q.db.QueryRow(ctx, insertPaymentOut,
		arg.Code,
		arg.BusinessType,
		arg.Amount,
		arg.FundAccountID,
		arg.RefType,
		arg.RefID,
		arg.Description,
		arg.Status,
		arg.BankReferenceID,
		arg.BookType,
		arg.CreatedBy,
	)
	var i InsertPaymentOutRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.TransactionDate,
		&i.Flow,
		&i.BusinessType,
		&i.Amount,
		&i.FundAccountID,
		&i.RefType,
		&i.RefID,
		&i.Description,
		&i.Status,
		&i.BankReferenceID,
		&i.BookType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsByRef = `-- name: ListPaymentsByRef :many
SELECT
    id, code, transaction_date, flow, business_type, amount, fund_account_id,
    ref_type, ref_id, description, status, bank_reference_id, book_type,
    created_by, created_at
FROM public.finance_transactions
WHERE ref_type = $1::text
  AND ref_id = $2::text
  AND deleted_at IS NULL
ORDER BY transaction_date DESC, id DESC
LIMIT $3::int
`

type ListPaymentsByRefParams struct {
	RefType  string
	RefID    string
	RowLimit int32
}

type ListPaymentsByRefRow struct {
	ID              int64
	Code            string
	TransactionDate pgtype.Timestamptz
	Flow            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         *string
	RefID           *string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
	CreatedAt       pgtype.Timestamptz
}

// Liệt kê phiếu thu/chi còn sống trỏ về MỘT chứng từ gốc (ref_type, ref_id) — cho
// HTTP đọc /v1/finance/transactions của 1 đơn. Sắp transaction_date DESC, id DESC
// (mới nhất trước, ổn định). Trả mọi flow/status để FE thấy đủ (UI tự lọc nếu cần).
func (q *Queries) ListPaymentsByRef(ctx context.Context, arg ListPaymentsByRefParams) ([]ListPaymentsByRefRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByRef, arg.RefType, arg.RefID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsByRefRow
	for rows.Next() {
		var i ListPaymentsByRefRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.TransactionDate,
			&i.Flow,
			&i.BusinessType,
			&i.Amount,
			&i.FundAccountID,
			&i.RefType,
			&i.RefID,
			&i.Description,
			&i.Status,
			&i.BankReferenceID,
			&i.BookType,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
