// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package appdb

import (
	"context"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE app.idempotency_keys
SET response_status = $2, response_body = $3, state = 'done', completed_at = now()
WHERE key = $1
`

type CompleteIdempotencyKeyParams struct {
	Key            string
	ResponseStatus *int32
	ResponseBody   []byte
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey, arg.Key, arg.ResponseStatus, arg.ResponseBody)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, response_status, response_body, state
FROM app.idempotency_keys
WHERE key = $1
`

type GetIdempotencyKeyRow struct {
	Key            string
	RequestHash    string
	ResponseStatus *int32
	ResponseBody   []byte
	State          string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.State,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO app.idempotency_keys (key, request_hash, state)
VALUES ($1, $2, 'in_progress')
ON CONFLICT (key) DO NOTHING
`

type InsertIdempotencyKeyParams struct {
	Key         string
	RequestHash string
}

// Begin: chèn key trạng thái in_progress; nếu key đã tồn tại thì bỏ qua
// (ON CONFLICT DO NOTHING) — giữ đúng behavior chống double-POST.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey, arg.Key, arg.RequestHash)
	return err
}
