// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO app.role_permissions (role_id, permission_id) VALUES ($1, $2)
`

type AssignPermissionToRoleParams struct {
	RoleID       string
	PermissionID string
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO app.user_roles (user_id, role_id) VALUES ($1, $2)
`

type AssignRoleToUserParams struct {
	UserID string
	RoleID string
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, used, revoked, expires_at, created_at
FROM app.refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AppRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i AppRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.Used,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, hash_algo, user_type, is_active, created_at, updated_at
FROM app.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HashAlgo,
		&i.UserType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, hash_algo, user_type, is_active, created_at, updated_at
FROM app.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HashAlgo,
		&i.UserType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPermission = `-- name: InsertPermission :one
INSERT INTO app.permissions (code, description) VALUES ($1, $2) RETURNING id
`

type InsertPermissionParams struct {
	Code        string
	Description *string
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPermission, arg.Code, arg.Description)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO app.refresh_tokens (id, user_id, token_hash, family_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	ID        string
	UserID    string
	TokenHash string
	FamilyID  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	return err
}

const insertRole = `-- name: InsertRole :one
INSERT INTO app.roles (code, name) VALUES ($1, $2) RETURNING id
`

type InsertRoleParams struct {
	Code string
	Name string
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, insertRole, arg.Code, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one

INSERT INTO app.users (email, password_hash, hash_algo, user_type, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertUserParams struct {
	Email        string
	PasswordHash string
	HashAlgo     string
	UserType     string
	IsActive     bool
}

// Các query phục vụ SEED dữ liệu test/integration (tạo user + gán quyền).
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (string, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.PasswordHash,
		arg.HashAlgo,
		arg.UserType,
		arg.IsActive,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE app.refresh_tokens
SET used = true
WHERE id = $1 AND used = false
`

// Claim NGUYÊN TỬ: chỉ đánh dấu used khi token còn used=false. Trả số dòng
// ảnh hưởng: 1 = claim thành công; 0 = đã used (mất race / reuse) → caller xử lý
// như reuse-detection. Điều kiện used=false là then chốt chống rotation race.
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const permissionCodesForUser = `-- name: PermissionCodesForUser :many
SELECT DISTINCT p.code
FROM app.user_roles ur
JOIN app.role_permissions rp ON rp.role_id = ur.role_id
JOIN app.permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.code
`

func (q *Queries) PermissionCodesForUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, permissionCodesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE app.refresh_tokens
SET revoked = true
WHERE family_id = $1
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE app.users
SET password_hash = $2, hash_algo = $3, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           string
	PasswordHash string
	HashAlgo     string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash, arg.HashAlgo)
	return err
}
