// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductInventoryStock = `-- name: AddProductInventoryStock :execrows

UPDATE public.product_inventory
SET stock_quantity = stock_quantity + $1::numeric,
    updated_at = now()
WHERE product_id = $2::bigint
  AND warehouse_id = $3::bigint
`

type AddProductInventoryStockParams struct {
	Qty         pgtype.Numeric
	ProductID   int64
	WarehouseID int64
}

// Tồn TỔNG nhập kho là UPSERT thủ công (bảng public.product_inventory KHÔNG có unique
// (warehouse,product) ở schema tham chiếu): repo gọi AddProductInventoryStock trước
// (cộng dồn nếu đã có dòng), nếu 0 dòng → InsertProductInventoryStock (tạo dòng mới).
// Cộng dồn tồn tổng cho (warehouse, product) ĐÃ CÓ dòng. Trả số dòng đổi: 0 → repo
// INSERT dòng mới (chưa có tồn cho cặp này).
func (q *Queries) AddProductInventoryStock(ctx context.Context, arg AddProductInventoryStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, addProductInventoryStock, arg.Qty, arg.ProductID, arg.WarehouseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deductInventoryBatch = `-- name: DeductInventoryBatch :exec
UPDATE public.inventory_batches
SET quantity = quantity - $1::numeric,
    updated_at = now()
WHERE id = $2::bigint
  AND quantity >= $1::numeric
`

type DeductInventoryBatchParams struct {
	Qty              pgtype.Numeric
	InventoryBatchID int64
}

// Trừ tồn của MỘT dòng tồn-theo-lô (inventory_batches) theo kế hoạch FEFO. Guard
// quantity >= @qty trong WHERE để KHÔNG bao giờ ghi âm dù có race (advisory lock
// đã chống, đây là phòng thủ tầng DB). Caller đã FOR UPDATE dòng này trong tx.
func (q *Queries) DeductInventoryBatch(ctx context.Context, arg DeductInventoryBatchParams) error {
	_, err := q.db.Exec(ctx, deductInventoryBatch, arg.Qty, arg.InventoryBatchID)
	return err
}

const deductProductInventory = `-- name: DeductProductInventory :exec
UPDATE public.product_inventory
SET stock_quantity = stock_quantity - $1::numeric,
    updated_at = now()
WHERE product_id = $2::bigint
  AND warehouse_id = $3::bigint
`

type DeductProductInventoryParams struct {
	Qty         pgtype.Numeric
	ProductID   int64
	WarehouseID int64
}

// Trừ tồn TỔNG (product_inventory.stock_quantity) của (warehouse, product) đúng
// tổng đã trừ qua các lô. Cập nhật theo (product_id, warehouse_id) — KHÓA tự nhiên
// của dòng tồn tổng (FOR UPDATE đã giữ dòng lô; advisory lock tuần tự hoá cả cụm).
func (q *Queries) DeductProductInventory(ctx context.Context, arg DeductProductInventoryParams) error {
	_, err := q.db.Exec(ctx, deductProductInventory, arg.Qty, arg.ProductID, arg.WarehouseID)
	return err
}

const insertBatch = `-- name: InsertBatch :one

INSERT INTO public.batches (id, product_id, batch_code, expiry_date, manufacturing_date, inbound_price)
VALUES (
    (SELECT COALESCE(MAX(id), 0) + 1 FROM public.batches),
    $1::bigint, $2::text,
    $3::date, $4::date,
    $5::numeric
)
RETURNING id
`

type InsertBatchParams struct {
	ProductID         int64
	BatchCode         string
	ExpiryDate        pgtype.Date
	ManufacturingDate pgtype.Date
	InboundPrice      pgtype.Numeric
}

// ============================================================================
// ĐƯỜNG GHI (NHẬP KHO — StockIn, đối xứng DeductFEFO). purchasing/POS gọi TRONG tx
// của họ (gộp atomic với post sổ + chi NCC). GHI bảng public.* (strangler, ADR 0001):
// batches (tạo LÔ mới + inbound_price = giá nhập per-unit), inventory_batches (tồn
// theo lô tại kho), product_inventory (tồn tổng — UPSERT). Advisory lock theo
// (warehouse, product) như DeductFEFO. KHÔNG float (numeric → decimal/money ở repo).
// ============================================================================
// Tạo MỘT lô mới (public.batches) khi nhập kho. id do DB sinh? KHÔNG: bảng cũ id =
// bigint NHƯNG ở schema tham chiếu test không có IDENTITY → dùng nextval của sequence
// ngầm? Để an toàn cross-env, lấy id = COALESCE(max+1) trong tx (advisory lock đã
// tuần tự hoá (kho,sp) — chống đua id cho cùng product). inbound_price = giá nhập
// per-unit của dòng PO. RETURNING id cho inventory_batches tham chiếu.
func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBatch,
		arg.ProductID,
		arg.BatchCode,
		arg.ExpiryDate,
		arg.ManufacturingDate,
		arg.InboundPrice,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertInventoryBatch = `-- name: InsertInventoryBatch :exec
INSERT INTO public.inventory_batches (id, warehouse_id, product_id, batch_id, quantity)
VALUES (
    (SELECT COALESCE(MAX(id), 0) + 1 FROM public.inventory_batches),
    $1::bigint, $2::bigint, $3::bigint, $4::numeric
)
`

type InsertInventoryBatchParams struct {
	WarehouseID int64
	ProductID   int64
	BatchID     int64
	Quantity    pgtype.Numeric
}

// Tạo dòng tồn-theo-lô (public.inventory_batches) cho (warehouse, product, batch) vừa
// tạo. id = COALESCE(max+1) (đồng nhất cách InsertBatch — bảng cũ id bigint không
// IDENTITY ở schema test). quantity = lượng nhập (NUMERIC).
func (q *Queries) InsertInventoryBatch(ctx context.Context, arg InsertInventoryBatchParams) error {
	_, err := q.db.Exec(ctx, insertInventoryBatch,
		arg.WarehouseID,
		arg.ProductID,
		arg.BatchID,
		arg.Quantity,
	)
	return err
}

const insertProductInventoryStock = `-- name: InsertProductInventoryStock :exec
INSERT INTO public.product_inventory (id, product_id, warehouse_id, stock_quantity)
VALUES (
    (SELECT COALESCE(MAX(id), 0) + 1 FROM public.product_inventory),
    $1::bigint, $2::bigint, $3::numeric
)
`

type InsertProductInventoryStockParams struct {
	ProductID   int64
	WarehouseID int64
	Qty         pgtype.Numeric
}

// Tạo dòng tồn tổng mới cho (warehouse, product) chưa có. id = COALESCE(max+1)
// (bảng id bigint không IDENTITY ở schema test). stock_quantity = qty nhập ban đầu.
func (q *Queries) InsertProductInventoryStock(ctx context.Context, arg InsertProductInventoryStockParams) error {
	_, err := q.db.Exec(ctx, insertProductInventoryStock, arg.ProductID, arg.WarehouseID, arg.Qty)
	return err
}

const listBatchesFEFO = `-- name: ListBatchesFEFO :many
SELECT
    ib.id            AS inventory_batch_id,
    ib.warehouse_id,
    ib.product_id,
    ib.batch_id,
    ib.quantity,
    b.batch_code,
    b.expiry_date,
    b.manufacturing_date,
    b.inbound_price
FROM public.inventory_batches ib
JOIN public.batches b ON b.id = ib.batch_id AND b.deleted_at IS NULL
WHERE ib.product_id = $1::bigint
  AND ib.quantity > 0
  AND ($2::bigint IS NULL OR ib.warehouse_id = $2::bigint)
ORDER BY b.expiry_date ASC, ib.batch_id ASC, ib.id ASC
`

type ListBatchesFEFOParams struct {
	ProductID   int64
	WarehouseID *int64
}

type ListBatchesFEFORow struct {
	InventoryBatchID  int64
	WarehouseID       int64
	ProductID         int64
	BatchID           int64
	Quantity          pgtype.Numeric
	BatchCode         string
	ExpiryDate        pgtype.Date
	ManufacturingDate pgtype.Date
	InboundPrice      pgtype.Numeric
}

// Danh sách LÔ còn tồn của một product theo FEFO (First-Expired-First-Out): sắp
// xếp HẠN DÙNG (batches.expiry_date) TĂNG DẦN — lô hết hạn trước đứng trước. Dữ
// liệu nền cho xuất kho FEFO sau này. Join inventory_batches (tồn theo lô tại kho)
// với batches (hạn dùng + giá nhập). Lọc lô đã xóa (batches.deleted_at IS NULL),
// chỉ lấy tồn > 0. Optional lọc warehouse_id. Tie-break theo batch_id rồi
// inventory_batches.id để thứ tự ổn định (deterministic).
func (q *Queries) ListBatchesFEFO(ctx context.Context, arg ListBatchesFEFOParams) ([]ListBatchesFEFORow, error) {
	rows, err := q.db.Query(ctx, listBatchesFEFO, arg.ProductID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchesFEFORow
	for rows.Next() {
		var i ListBatchesFEFORow
		if err := rows.Scan(
			&i.InventoryBatchID,
			&i.WarehouseID,
			&i.ProductID,
			&i.BatchID,
			&i.Quantity,
			&i.BatchCode,
			&i.ExpiryDate,
			&i.ManufacturingDate,
			&i.InboundPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchesForDeductFEFO = `-- name: ListBatchesForDeductFEFO :many
SELECT
    ib.id            AS inventory_batch_id,
    ib.warehouse_id,
    ib.product_id,
    ib.batch_id,
    ib.quantity,
    b.batch_code,
    b.expiry_date,
    b.manufacturing_date,
    b.inbound_price
FROM public.inventory_batches ib
JOIN public.batches b ON b.id = ib.batch_id AND b.deleted_at IS NULL
WHERE ib.warehouse_id = $1::bigint
  AND ib.product_id = $2::bigint
  AND ib.quantity > 0
ORDER BY b.expiry_date ASC, ib.batch_id ASC, ib.id ASC
FOR UPDATE OF ib
`

type ListBatchesForDeductFEFOParams struct {
	WarehouseID int64
	ProductID   int64
}

type ListBatchesForDeductFEFORow struct {
	InventoryBatchID  int64
	WarehouseID       int64
	ProductID         int64
	BatchID           int64
	Quantity          pgtype.Numeric
	BatchCode         string
	ExpiryDate        pgtype.Date
	ManufacturingDate pgtype.Date
	InboundPrice      pgtype.Numeric
}

// Các lô CÒN TỒN của (warehouse, product) theo FEFO (expiry ASC) ĐỂ TRỪ, giữ dòng
// bằng FOR UPDATE OF ib (khoá dòng tồn-theo-lô trong tx — không khoá batches để
// khỏi chặn đọc lô). Lọc lô đã xóa (batches.deleted_at IS NULL) + tồn > 0. Khác
// ListBatchesFEFO (đọc): BẮT BUỘC warehouse_id (trừ kho theo đúng 1 kho) + FOR
// UPDATE. Tie-break batch_id rồi ib.id cho thứ tự ổn định.
func (q *Queries) ListBatchesForDeductFEFO(ctx context.Context, arg ListBatchesForDeductFEFOParams) ([]ListBatchesForDeductFEFORow, error) {
	rows, err := q.db.Query(ctx, listBatchesForDeductFEFO, arg.WarehouseID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchesForDeductFEFORow
	for rows.Next() {
		var i ListBatchesForDeductFEFORow
		if err := rows.Scan(
			&i.InventoryBatchID,
			&i.WarehouseID,
			&i.ProductID,
			&i.BatchID,
			&i.Quantity,
			&i.BatchCode,
			&i.ExpiryDate,
			&i.ManufacturingDate,
			&i.InboundPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStock = `-- name: ListStock :many
SELECT
    pi.id,
    pi.product_id,
    pi.warehouse_id,
    pi.stock_quantity,
    pi.min_stock,
    pi.max_stock,
    pi.shelf_location,
    pi.updated_at
FROM public.product_inventory pi
JOIN public.warehouses w ON w.id = pi.warehouse_id AND w.deleted_at IS NULL
WHERE pi.id > $1::bigint
  AND pi.product_id IS NOT NULL
  AND ($2::bigint IS NULL OR pi.product_id = $2::bigint)
  AND ($3::bigint IS NULL OR pi.warehouse_id = $3::bigint)
ORDER BY pi.id ASC
LIMIT $4::int
`

type ListStockParams struct {
	AfterID     int64
	ProductID   *int64
	WarehouseID *int64
	RowLimit    int32
}

type ListStockRow struct {
	ID            int64
	ProductID     *int64
	WarehouseID   *int64
	StockQuantity pgtype.Numeric
	MinStock      *int32
	MaxStock      *int32
	ShelfLocation *string
	UpdatedAt     pgtype.Timestamptz
}

// Tồn TỔNG theo kho (public.product_inventory.stock_quantity). Keyset theo id ASC
// (id > after_id). Lọc optional product_id và/hoặc warehouse_id. Chỉ lấy dòng có
// product_id và warehouse_id NOT NULL (dòng tồn hợp lệ) — cột này nullable ở DB.
// KHÔNG có deleted_at ở product_inventory; nhưng loại tồn của kho đã đóng
// (warehouses.deleted_at) qua JOIN để không lộ tồn kho không còn dùng.
func (q *Queries) ListStock(ctx context.Context, arg ListStockParams) ([]ListStockRow, error) {
	rows, err := q.db.Query(ctx, listStock,
		arg.AfterID,
		arg.ProductID,
		arg.WarehouseID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockRow
	for rows.Next() {
		var i ListStockRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.WarehouseID,
			&i.StockQuantity,
			&i.MinStock,
			&i.MaxStock,
			&i.ShelfLocation,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouses = `-- name: ListWarehouses :many

SELECT
    id, key, name, unit, address, type, code, manager, phone, status,
    company_id, outlet_type, created_at
FROM public.warehouses
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
ORDER BY id ASC
LIMIT $2::int
`

type ListWarehousesParams struct {
	Status   *string
	RowLimit int32
}

type ListWarehousesRow struct {
	ID         int64
	Key        string
	Name       string
	Unit       string
	Address    *string
	Type       string
	Code       *string
	Manager    *string
	Phone      *string
	Status     string
	CompanyID  *string
	OutletType *string
	CreatedAt  pgtype.Timestamptz
}

// Inventory (LÁT ĐỌC, ADR 0001): ĐỌC bảng public.* kế thừa. CHƯA có đường GHI
// (trừ kho FEFO/nhập/chuyển/kiểm kê HOÃN — cần khoá tranh chấp + tx tiền, làm
// sau module orders). quantity/stock_quantity là NUMERIC → map sang kiểu decimal
// (domain.Quantity) ở repo, KHÔNG dùng float. inbound_price (giá vốn lô) là
// numeric → common/money ở repo, KHÔNG float.
// Danh sách kho/chi nhánh còn hoạt động (lọc deleted_at IS NULL). Lọc optional
// status. Sắp theo id ASC cho ổn định. Không phân trang (số kho nhỏ, có chặn).
func (q *Queries) ListWarehouses(ctx context.Context, arg ListWarehousesParams) ([]ListWarehousesRow, error) {
	rows, err := q.db.Query(ctx, listWarehouses, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWarehousesRow
	for rows.Next() {
		var i ListWarehousesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Unit,
			&i.Address,
			&i.Type,
			&i.Code,
			&i.Manager,
			&i.Phone,
			&i.Status,
			&i.CompanyID,
			&i.OutletType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWarehouseProduct = `-- name: LockWarehouseProduct :exec

SELECT pg_advisory_xact_lock(
    hashtext($1::bigint || ':' || $2::bigint)
)
`

type LockWarehouseProductParams struct {
	WarehouseID int64
	ProductID   int64
}

// ============================================================================
// ĐƯỜNG GHI (P2 — trừ kho FEFO, có khoá tranh chấp). Chạy TRONG tx do caller
// (orders/POS) truyền — gộp atomic với post sổ + ghi tiền. GHI bảng public.*
// (strangler, ADR 0001): inventory_batches.quantity + product_inventory.stock_quantity.
// lock_version các bảng này là migrate-later → dùng SELECT ... FOR UPDATE +
// pg_advisory_xact_lock để tuần tự hoá, chống bán âm khi đồng thời. KHÔNG float
// (quantity NUMERIC → decimal ở repo).
// ============================================================================
// Khoá tranh chấp ĐẦU TX cho một (warehouse, product): pg_advisory_xact_lock giữ
// tới khi tx commit/rollback. Tuần tự hoá MỌI giao dịch trừ kho cùng (kho,sp) →
// chỉ một tx trừ tại một thời điểm (chống bán âm). hashtext gộp 2 khoá thành 1
// chuỗi 'warehouse:product' rồi băm sang bigint cho advisory lock (1 tham số).
func (q *Queries) LockWarehouseProduct(ctx context.Context, arg LockWarehouseProductParams) error {
	_, err := q.db.Exec(ctx, lockWarehouseProduct, arg.WarehouseID, arg.ProductID)
	return err
}
