// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package appdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAccountingPeriod struct {
	ID     string
	Year   int32
	Month  int32
	Status string
}

type AppFinanceTransactionAllocation struct {
	ID        string
	PaymentID int64
	OrderCode string
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type AppIdempotencyKey struct {
	Key            string
	RequestHash    string
	ResponseStatus *int32
	ResponseBody   []byte
	State          string
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type AppInvoiceSerial struct {
	Serial string
	MauSo  string
	NextNo int64
}

type AppJournalEntry struct {
	ID         string
	Book       string
	EntryDate  pgtype.Date
	PeriodID   string
	SourceType string
	SourceID   string
	Memo       string
	CreatedAt  pgtype.Timestamptz
}

type AppJournalEntryLine struct {
	ID          string
	EntryID     string
	LineNo      int32
	AccountCode string
	Debit       pgtype.Numeric
	Credit      pgtype.Numeric
}

type AppOrderIdempotency struct {
	IdemKey   string
	OrderID   string
	OrderCode string
	CreatedAt pgtype.Timestamptz
}

type AppPermission struct {
	ID          string
	Code        string
	Description *string
}

type AppPurchaseOrder struct {
	ID           string
	Code         string
	SupplierID   *int64
	SupplierName *string
	Status       string
	TotalAmount  pgtype.Numeric
	VatAmount    pgtype.Numeric
	Note         *string
	LockVersion  int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type AppPurchaseOrderIdempotency struct {
	IdemKey   string
	PoID      string
	PoCode    string
	CreatedAt pgtype.Timestamptz
}

type AppPurchaseOrderItem struct {
	ID                string
	PoID              string
	LineNo            int32
	ProductID         int64
	Quantity          pgtype.Numeric
	UnitCost          pgtype.Numeric
	VatRate           pgtype.Numeric
	BatchCode         *string
	ExpiryDate        pgtype.Date
	ManufacturingDate pgtype.Date
	LineTotal         pgtype.Numeric
}

type AppRefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	FamilyID  string
	Used      bool
	Revoked   bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AppRole struct {
	ID   string
	Code string
	Name string
}

type AppRolePermission struct {
	RoleID       string
	PermissionID string
}

type AppSalesInvoice struct {
	ID              string
	OrderCode       string
	CustomerTaxCode string
	Serial          string
	InvoiceNo       int64
	IssueDate       pgtype.Date
	Subtotal        pgtype.Numeric
	VatAmount       pgtype.Numeric
	Total           pgtype.Numeric
	Status          string
	LockVersion     int32
	CreatedAt       pgtype.Timestamptz
}

type AppSalesInvoiceLine struct {
	ID          string
	InvoiceID   string
	LineNo      int32
	ProductID   int64
	Description string
	Quantity    pgtype.Numeric
	UnitPrice   pgtype.Numeric
	VatRate     pgtype.Numeric
	LineAmount  pgtype.Numeric
	LineVat     pgtype.Numeric
}

type AppUser struct {
	ID           string
	Email        string
	PasswordHash string
	HashAlgo     string
	UserType     string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AppUserRole struct {
	UserID string
	RoleID string
}

type Batch struct {
	ID                int64
	ProductID         int64
	BatchCode         string
	ExpiryDate        pgtype.Date
	ManufacturingDate pgtype.Date
	InboundPrice      pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type Category struct {
	ID        int64
	Name      string
	Slug      string
	ParentID  *int64
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ChartOfAccount struct {
	ID           string
	AccountCode  string
	Name         string
	ParentID     *string
	Type         string
	BalanceType  string
	Status       string
	AllowPosting bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type Customer struct {
	ID            int64
	CustomerCode  *string
	Name          string
	CustomerType  string
	Phone         *string
	Email         *string
	Address       *string
	Status        string
	Dob           pgtype.Date
	Gender        *string
	Cccd          *string
	LoyaltyPoints *int32
	B2bMetadata   []byte
	CurrentDebt   pgtype.Numeric
	UpdatedBy     *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type FinanceTransaction struct {
	ID              int64
	Code            string
	TransactionDate pgtype.Timestamptz
	Flow            string
	BusinessType    string
	Amount          pgtype.Numeric
	FundAccountID   int64
	RefType         *string
	RefID           *string
	Description     *string
	Status          string
	BankReferenceID *string
	BookType        string
	CreatedBy       *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type FundAccount struct {
	ID             int64
	Name           string
	Type           string
	AccountNumber  *string
	BankID         *int64
	InitialBalance pgtype.Numeric
	Balance        pgtype.Numeric
	Currency       *string
	Status         string
	AccountID      *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type InventoryBatch struct {
	ID          int64
	WarehouseID int64
	ProductID   int64
	BatchID     int64
	Quantity    pgtype.Numeric
	UpdatedAt   pgtype.Timestamptz
}

type Manufacturer struct {
	ID        int64
	Name      string
	Slug      string
	Country   *string
	LogoUrl   *string
	Status    *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Order struct {
	ID            string
	Code          string
	CustomerID    *int64
	CreatorID     *string
	Status        string
	OrderType     string
	TotalAmount   pgtype.Numeric
	FinalAmount   pgtype.Numeric
	PaymentStatus *string
	Note          *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type OrderItem struct {
	ID               string
	OrderID          string
	ProductID        int64
	Quantity         int32
	Uom              string
	ConversionFactor *int32
	BaseQuantity     *int32
	UnitPrice        pgtype.Numeric
	Discount         pgtype.Numeric
	IsGift           *bool
	Note             *string
	BatchNo          *string
	ExpiryDate       pgtype.Date
	TotalLine        pgtype.Numeric
	QuantityPicked   *int32
	QuantityReturned *int32
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Product struct {
	ID                   int64
	Name                 string
	Sku                  *string
	Barcode              *string
	Description          *string
	ActiveIngredient     *string
	ImageUrl             *string
	Status               string
	Fts                  interface{}
	CategoryID           *int64
	ManufacturerID       *int64
	CategoryName         *string
	ManufacturerName     *string
	DistributorID        *int64
	InvoicePrice         pgtype.Numeric
	ActualCost           pgtype.Numeric
	WholesaleUnit        *string
	RetailUnit           *string
	ConversionFactor     *int32
	WholesaleMarginValue pgtype.Numeric
	WholesaleMarginType  *string
	RetailMarginValue    pgtype.Numeric
	RetailMarginType     *string
	ItemsPerCarton       *int32
	CartonWeight         pgtype.Numeric
	CartonDimensions     *string
	PurchasingPolicy     *string
	RegistrationNumber   *string
	PackingSpec          *string
	StockManagementType  *string
	WholesaleMarginRate  pgtype.Numeric
	RetailMarginRate     pgtype.Numeric
	UsageInstructions    []byte
	StockStatus          *string
	ProductImages        []string
	UpdatedBy            *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type ProductInventory struct {
	ID              int64
	ProductID       *int64
	WarehouseID     *int64
	StockQuantity   pgtype.Numeric
	MinStock        *int32
	MaxStock        *int32
	ShelfLocation   *string
	LocationCabinet *string
	LocationRow     *string
	LocationSlot    *string
	UpdatedBy       *string
	UpdatedAt       pgtype.Timestamptz
}

type ProductUnit struct {
	ID             int64
	ProductID      *int64
	UnitName       string
	ConversionRate *int32
	Barcode        *string
	IsBase         *bool
	IsDirectSale   *bool
	PriceCost      pgtype.Numeric
	PriceSell      pgtype.Numeric
	UnitType       *string
	Price          pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Warehouse struct {
	ID         int64
	Key        string
	Name       string
	Unit       string
	Address    *string
	Type       string
	Latitude   pgtype.Numeric
	Longitude  pgtype.Numeric
	Code       *string
	Manager    *string
	Phone      *string
	Status     string
	CompanyID  *string
	OutletType *string
	CreatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}
