// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findOrderByIdemKey = `-- name: FindOrderByIdemKey :one
SELECT order_id, order_code
FROM app.order_idempotency
WHERE idem_key = $1::text
`

type FindOrderByIdemKeyRow struct {
	OrderID   string
	OrderCode string
}

// Tra cứu đơn đã tạo theo Idempotency-Key (chống tạo trùng). Có → trả order_id +
// code (app đọc lại đơn cũ). Không có → ErrNoRows (được phép tạo mới).
func (q *Queries) FindOrderByIdemKey(ctx context.Context, idemKey string) (FindOrderByIdemKeyRow, error) {
	row := q.db.QueryRow(ctx, findOrderByIdemKey, idemKey)
	var i FindOrderByIdemKeyRow
	err := row.Scan(&i.OrderID, &i.OrderCode)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    o.id,
    o.code,
    o.customer_id,
    o.creator_id,
    o.status,
    o.order_type,
    o.total_amount,
    o.final_amount,
    o.payment_status,
    o.note,
    o.created_at,
    o.updated_at,
    app.order_paid_amount(o.code) AS paid_amount
FROM public.orders o
WHERE o.id = $1::uuid AND o.deleted_at IS NULL
`

type GetOrderByIDRow struct {
	ID            string
	Code          string
	CustomerID    *int64
	CreatorID     *string
	Status        string
	OrderType     string
	TotalAmount   pgtype.Numeric
	FinalAmount   pgtype.Numeric
	PaymentStatus *string
	Note          *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	PaidAmount    pgtype.Numeric
}

// Một đơn theo id (uuid) chưa soft-delete, kèm paid_amount suy diễn.
func (q *Queries) GetOrderByID(ctx context.Context, orderID string) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerID,
		&i.CreatorID,
		&i.Status,
		&i.OrderType,
		&i.TotalAmount,
		&i.FinalAmount,
		&i.PaymentStatus,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAmount,
	)
	return i, err
}

const getOrderHeaderForUpdate = `-- name: GetOrderHeaderForUpdate :one

SELECT id, code, customer_id, creator_id, status, order_type,
    total_amount, final_amount, payment_status
FROM public.orders
WHERE id = $1::uuid AND deleted_at IS NULL
FOR UPDATE
`

type GetOrderHeaderForUpdateRow struct {
	ID            string
	Code          string
	CustomerID    *int64
	CreatorID     *string
	Status        string
	OrderType     string
	TotalAmount   pgtype.Numeric
	FinalAmount   pgtype.Numeric
	PaymentStatus *string
}

// ============================================================================
// ĐƯỜNG GHI ORCHESTRATION (P4b — gộp cross-module trong 1 tx: ShipOrder /
// RecordPayment / CreatePosSale). Trừ kho FEFO + phát HĐ VAT + post sổ kép +
// ghi phiếu thu gọi qua PORT module khác (inventory/vat/accounting/finance) —
// KHÔNG có SQL ở đây cho các bảng đó. Riêng orders cần: KHOÁ + đọc header đầy đủ
// (FOR UPDATE) và cập nhật payment_status suy diễn.
// ============================================================================
// Lấy header đơn ĐẦY ĐỦ (code/status/order_type/customer_id/final_amount) + KHOÁ
// dòng (FOR UPDATE) trong tx — dùng cho ShipOrder/RecordPayment để vừa khoá vừa
// đọc các trường cần điều phối (mã đơn cho ref/HĐ, loại đơn B2B/B2C cho luồng
// post sổ, tổng phải trả để tính payment_status). Không thấy → ErrNoRows
// (app map NotFound). KHÔNG khoá theo paid_amount (suy diễn động, đọc riêng).
func (q *Queries) GetOrderHeaderForUpdate(ctx context.Context, orderID string) (GetOrderHeaderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrderHeaderForUpdate, orderID)
	var i GetOrderHeaderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerID,
		&i.CreatorID,
		&i.Status,
		&i.OrderType,
		&i.TotalAmount,
		&i.FinalAmount,
		&i.PaymentStatus,
	)
	return i, err
}

const getOrderStatusForUpdate = `-- name: GetOrderStatusForUpdate :one
SELECT id, status
FROM public.orders
WHERE id = $1::uuid AND deleted_at IS NULL
FOR UPDATE
`

type GetOrderStatusForUpdateRow struct {
	ID     string
	Status string
}

// Lấy status hiện tại của đơn (chưa xoá mềm) và KHOÁ dòng (FOR UPDATE) trong tx
// để đổi trạng thái an toàn (tuần tự hoá các thao tác đồng thời trên cùng đơn).
// Không thấy → ErrNoRows (app map NotFound).
func (q *Queries) GetOrderStatusForUpdate(ctx context.Context, orderID string) (GetOrderStatusForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrderStatusForUpdate, orderID)
	var i GetOrderStatusForUpdateRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO public.orders (
    id, code, customer_id, creator_id, status, order_type,
    total_amount, final_amount, payment_status, note
) VALUES (
    $1::uuid, $2::text, $3::bigint,
    $4::uuid, $5::text, $6::text,
    $7::numeric, $8::numeric, 'unpaid', $9::text
)
RETURNING id, code, customer_id, creator_id, status, order_type,
    total_amount, final_amount, payment_status, note, created_at, updated_at
`

type InsertOrderParams struct {
	ID          string
	Code        string
	CustomerID  *int64
	CreatorID   *string
	Status      string
	OrderType   string
	TotalAmount pgtype.Numeric
	FinalAmount pgtype.Numeric
	Note        *string
}

type InsertOrderRow struct {
	ID            string
	Code          string
	CustomerID    *int64
	CreatorID     *string
	Status        string
	OrderType     string
	TotalAmount   pgtype.Numeric
	FinalAmount   pgtype.Numeric
	PaymentStatus *string
	Note          *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Ghi MỘT đơn (status PENDING). id + code do APP sinh (uuid v7 + tiền tố/seq) →
// truyền vào (KHÔNG dùng default DB). customer_id/creator_id/note nullable. total_
// amount/final_amount NUMERIC (đã tính ở domain). created_at/updated_at để DB
// default now(). Trùng code (UNIQUE WHERE deleted_at IS NULL) → unique violation
// (app xử lý). RETURNING các cột cần để map về domain + đường đọc.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (InsertOrderRow, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.Code,
		arg.CustomerID,
		arg.CreatorID,
		arg.Status,
		arg.OrderType,
		arg.TotalAmount,
		arg.FinalAmount,
		arg.Note,
	)
	var i InsertOrderRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerID,
		&i.CreatorID,
		&i.Status,
		&i.OrderType,
		&i.TotalAmount,
		&i.FinalAmount,
		&i.PaymentStatus,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderAllocation = `-- name: InsertOrderAllocation :exec

INSERT INTO app.finance_transaction_allocations (payment_id, order_code, amount)
VALUES ($1::bigint, $2::text, $3::numeric)
ON CONFLICT (payment_id, order_code) DO NOTHING
`

type InsertOrderAllocationParams struct {
	PaymentID int64
	OrderCode string
	Amount    pgtype.Numeric
}

// ============================================================================
// PHÂN BỔ 1 phiếu THU → NHIỀU đơn (spec mục 55). Phiếu lump-sum (ref_type='customer')
// phân bổ cho các đơn chưa tất toán, CŨ NHẤT trước. "Đã thu mỗi đơn" = phiếu trực
// tiếp + allocation (qua app.order_paid_amount).
// ============================================================================
// Ghi MỘT dòng phân bổ phiếu (payment_id) cho một đơn (order_code) số tiền amount.
// 1 phiếu × 1 đơn tối đa một dòng (UNIQUE). ON CONFLICT DO NOTHING → IDEMPOTENT: gọi
// lại (replay) KHÔNG cộng dồn (tránh nhân đôi "đã thu"). amount > 0 (CHECK ở bảng).
func (q *Queries) InsertOrderAllocation(ctx context.Context, arg InsertOrderAllocationParams) error {
	_, err := q.db.Exec(ctx, insertOrderAllocation, arg.PaymentID, arg.OrderCode, arg.Amount)
	return err
}

const insertOrderIdemKey = `-- name: InsertOrderIdemKey :exec
INSERT INTO app.order_idempotency (idem_key, order_id, order_code)
VALUES ($1::text, $2::uuid, $3::text)
ON CONFLICT (idem_key) DO NOTHING
`

type InsertOrderIdemKeyParams struct {
	IdemKey   string
	OrderID   string
	OrderCode string
}

// Ghi ánh xạ Idempotency-Key → đơn vừa tạo. ON CONFLICT DO NOTHING chống race
// (2 luồng cùng key): luồng thua không ghi đè, app phát hiện qua RowsAffected/
// re-SELECT để trả đơn của luồng thắng. KHÔNG cộng/ghi gì thêm.
func (q *Queries) InsertOrderIdemKey(ctx context.Context, arg InsertOrderIdemKeyParams) error {
	_, err := q.db.Exec(ctx, insertOrderIdemKey, arg.IdemKey, arg.OrderID, arg.OrderCode)
	return err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO public.order_items (
    id, order_id, product_id, quantity, uom, unit_price, discount, total_line, is_gift
) VALUES (
    $1::uuid, $2::uuid, $3::bigint, $4::integer,
    $5::text, $6::numeric, $7::numeric, $8::numeric, false
)
`

type InsertOrderItemParams struct {
	ID        string
	OrderID   string
	ProductID int64
	Quantity  int32
	Uom       string
	UnitPrice pgtype.Numeric
	Discount  pgtype.Numeric
	TotalLine pgtype.Numeric
}

// Ghi MỘT dòng hàng của đơn. id app sinh (uuid v7). quantity là INTEGER (cột
// thật). unit_price/discount/total_line NUMERIC (đã tính ở domain). is_gift mặc
// định false ở P4a (chưa làm hàng tặng). created_at để DB default now().
func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Uom,
		arg.UnitPrice,
		arg.Discount,
		arg.TotalLine,
	)
	return err
}

const listOrderLines = `-- name: ListOrderLines :many
SELECT
    oi.id,
    oi.product_id,
    oi.quantity,
    oi.uom,
    oi.unit_price,
    oi.discount,
    oi.total_line,
    oi.is_gift,
    oi.batch_no,
    oi.expiry_date,
    oi.note
FROM public.order_items oi
WHERE oi.order_id = $1::uuid
  AND oi.deleted_at IS NULL
ORDER BY oi.created_at ASC, oi.id ASC
`

type ListOrderLinesRow struct {
	ID         string
	ProductID  int64
	Quantity   int32
	Uom        string
	UnitPrice  pgtype.Numeric
	Discount   pgtype.Numeric
	TotalLine  pgtype.Numeric
	IsGift     *bool
	BatchNo    *string
	ExpiryDate pgtype.Date
	Note       *string
}

// Dòng hàng của một đơn (chưa soft-delete), thứ tự ổn định (created_at, id).
func (q *Queries) ListOrderLines(ctx context.Context, orderID string) ([]ListOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderLinesRow
	for rows.Next() {
		var i ListOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Quantity,
			&i.Uom,
			&i.UnitPrice,
			&i.Discount,
			&i.TotalLine,
			&i.IsGift,
			&i.BatchNo,
			&i.ExpiryDate,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many

SELECT
    o.id,
    o.code,
    o.customer_id,
    o.creator_id,
    o.status,
    o.order_type,
    o.total_amount,
    o.final_amount,
    o.payment_status,
    o.note,
    o.created_at,
    o.updated_at,
    app.order_paid_amount(o.code) AS paid_amount
FROM public.orders o
WHERE o.deleted_at IS NULL
  AND (
        $1::timestamptz IS NULL
        OR o.created_at < $1::timestamptz
        OR (o.created_at = $1::timestamptz
            AND o.id < $2::uuid)
      )
  AND ($3::bigint IS NULL OR o.customer_id = $3::bigint)
  AND ($4::text IS NULL OR o.status = $4::text)
  AND ($5::text IS NULL OR o.payment_status = $5::text)
  AND ($6::timestamptz IS NULL OR o.created_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR o.created_at <= $7::timestamptz)
ORDER BY o.created_at DESC, o.id DESC
LIMIT $8::int
`

type ListOrdersParams struct {
	AfterCreatedAt pgtype.Timestamptz
	AfterID        *string
	CustomerID     *int64
	Status         *string
	PaymentStatus  *string
	FromDate       pgtype.Timestamptz
	ToDate         pgtype.Timestamptz
	RowLimit       int32
}

type ListOrdersRow struct {
	ID            string
	Code          string
	CustomerID    *int64
	CreatorID     *string
	Status        string
	OrderType     string
	TotalAmount   pgtype.Numeric
	FinalAmount   pgtype.Numeric
	PaymentStatus *string
	Note          *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	PaidAmount    pgtype.Numeric
}

// Orders (ĐỌC + GHI nền P4a, ADR 0001): ĐỌC bảng public.* kế thừa; GHI tạo đơn +
// đổi trạng thái ĐƠN GIẢN (xem khối "ĐƯỜNG GHI" cuối file). Trừ kho FEFO, ghi
// phiếu thu, post sổ, POS atomic (ShipOrder/RecordPayment) HOÃN sang P4b (cần
// cross-module). Tiền (total_amount/final_amount/unit_price/discount/total_line/amount) là
// NUMERIC → common/money ở repo, KHÔNG float. order_items.quantity là INTEGER →
// domain.Quantity (decimal) ở repo.
//
// "ĐÃ THU" của đơn = tổng phiếu THU đã hoàn tất trỏ về đơn qua
//
//	(ref_type='order' AND ref_id = orders.code)  [ref_id là TEXT = MÃ đơn]
//
// lọc:  lower(flow)='in'  (ERP set 'in' lowercase; so khớp case-insensitive cho
// an toàn vì doc ghi 'IN'),  status='completed'  (tiền đã thực vào quỹ),
// deleted_at IS NULL,  book_type IN ('INTERNAL','BOTH')  → SỔ THỰC TẾ (giả định
// cần xác nhận business). orders KHÔNG có paid_amount → đây là suy diễn read-only.
// Keyset pagination theo (created_at DESC, id DESC): trang kế lấy đơn "cũ hơn"
// mốc cursor — (created_at < @after_created_at) OR (created_at = @after_created_at
// AND id < @after_id). @after_created_at NULL = trang đầu (lấy từ mới nhất). Lọc
// optional customer_id, status, payment_status, khoảng created_at [from_date,
// to_date]. Mỗi đơn kèm paid_amount (subquery aggregate finance_transactions).
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.CustomerID,
		arg.Status,
		arg.PaymentStatus,
		arg.FromDate,
		arg.ToDate,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CustomerID,
			&i.CreatorID,
			&i.Status,
			&i.OrderType,
			&i.TotalAmount,
			&i.FinalAmount,
			&i.PaymentStatus,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpaidOrdersByCustomerForUpdate = `-- name: ListUnpaidOrdersByCustomerForUpdate :many
SELECT o.id, o.code, o.final_amount, app.order_paid_amount(o.code) AS paid_amount
FROM public.orders o
WHERE o.customer_id = $1::bigint
  AND o.payment_status <> 'paid'
  AND o.deleted_at IS NULL
ORDER BY o.created_at ASC, o.id ASC
FOR UPDATE
`

type ListUnpaidOrdersByCustomerForUpdateRow struct {
	ID          string
	Code        string
	FinalAmount pgtype.Numeric
	PaidAmount  pgtype.Numeric
}

// Đơn CHƯA tất toán (payment_status <> 'paid') của một khách, CŨ NHẤT trước (mục
// 55) + KHOÁ dòng (FOR UPDATE) để phân bổ tuần tự an toàn. Kèm final_amount + đã-thu
// hiện tại (app.order_paid_amount) để app tính phần còn thiếu mỗi đơn.
func (q *Queries) ListUnpaidOrdersByCustomerForUpdate(ctx context.Context, customerID int64) ([]ListUnpaidOrdersByCustomerForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listUnpaidOrdersByCustomerForUpdate, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpaidOrdersByCustomerForUpdateRow
	for rows.Next() {
		var i ListUnpaidOrdersByCustomerForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.FinalAmount,
			&i.PaidAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderCodeSeq = `-- name: NextOrderCodeSeq :one

SELECT nextval('app.order_code_seq')::bigint AS seq
`

// ============================================================================
// ĐƯỜNG GHI (P4a — tạo đơn + state machine ĐƠN GIẢN, ADR 0001 strangler). Chạy
// TRONG tx do app mở (platform/db.WithinTx). GHI bảng public.orders + order_items
// (mã đơn app tự sinh từ app.order_code_seq + tiền tố; id uuid v7 app-side). Đổi
// trạng thái dùng SELECT ... FOR UPDATE (lock_version orders là migrate-later).
// Idempotency tạo đơn qua app.order_idempotency (1 Idempotency-Key → 1 đơn).
// KHÔNG đụng kho/tiền/sổ (ShipOrder/RecordPayment/POS = P4b). Tiền NUMERIC →
// common/money ở repo, KHÔNG float. quantity INTEGER (cột thật) → ghi từ int.
// ============================================================================
// Cấp số tăng dần kế tiếp cho mã đơn (app ghép tiền tố + zero-pad). Sequence bảo
// đảm KHÔNG trùng, an toàn đua (mỗi nextval một giá trị duy nhất).
func (q *Queries) NextOrderCodeSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextOrderCodeSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const sumOrderPaidInTx = `-- name: SumOrderPaidInTx :one
SELECT app.order_paid_amount($1::text)::numeric AS paid_amount
`

// Tổng ĐÃ THU của đơn theo mã (ref_id = orders.code) TRONG tx hiện hành — phiếu/
// allocation vừa ghi cùng tx ĐƯỢC tính (visibility trong tx). Gọi NGUỒN CHÂN LÝ
// app.order_paid_amount (phiếu trực tiếp + phân bổ; flow='in', status pending+
// completed, sổ INTERNAL/BOTH). Dùng tính lại payment_status sau RecordPaymentIn.
func (q *Queries) SumOrderPaidInTx(ctx context.Context, orderCode string) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumOrderPaidInTx, orderCode)
	var paid_amount pgtype.Numeric
	err := row.Scan(&paid_amount)
	return paid_amount, err
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :execrows
UPDATE public.orders
SET payment_status = $1::text, updated_at = now()
WHERE id = $2::uuid
  AND deleted_at IS NULL
`

type UpdateOrderPaymentStatusParams struct {
	PaymentStatus string
	OrderID       string
}

// Cập nhật payment_status suy diễn (unpaid/partial/paid) + updated_at. KHÔNG đụng
// status xử lý đơn. Chỉ ghi đơn còn sống. RowsAffected=0 nếu đơn biến mất (phòng thủ).
func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderPaymentStatus, arg.PaymentStatus, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE public.orders
SET status = $1::text, updated_at = now()
WHERE id = $2::uuid
  AND status = $3::text
  AND deleted_at IS NULL
`

type UpdateOrderStatusParams struct {
	NewStatus      string
	OrderID        string
	ExpectedStatus string
}

// Cập nhật trạng thái đơn (+ updated_at). Guard status cũ trong WHERE (optimistic
// theo giá trị đã đọc dưới FOR UPDATE) — RowsAffected=0 nếu đơn đã đổi trạng thái
// bởi luồng khác (app map Conflict). KHÔNG ghi đè đơn đã xoá mềm.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus, arg.NewStatus, arg.OrderID, arg.ExpectedStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
