// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchasing.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPurchaseOrderByIdemKey = `-- name: FindPurchaseOrderByIdemKey :one
SELECT po_id, po_code FROM app.purchase_order_idempotency
WHERE idem_key = $1::text
`

type FindPurchaseOrderByIdemKeyRow struct {
	PoID   string
	PoCode string
}

// Tra PO đã tạo theo Idempotency-Key (idempotent tạo PO). Không thấy → ErrNoRows.
func (q *Queries) FindPurchaseOrderByIdemKey(ctx context.Context, idemKey string) (FindPurchaseOrderByIdemKeyRow, error) {
	row := q.db.QueryRow(ctx, findPurchaseOrderByIdemKey, idemKey)
	var i FindPurchaseOrderByIdemKeyRow
	err := row.Scan(&i.PoID, &i.PoCode)
	return i, err
}

const getPurchaseOrderByID = `-- name: GetPurchaseOrderByID :one
SELECT id, code, supplier_id, supplier_name, status, total_amount, vat_amount,
       note, lock_version, created_at, updated_at
FROM app.purchase_orders
WHERE id = $1::uuid AND deleted_at IS NULL
`

type GetPurchaseOrderByIDRow struct {
	ID           string
	Code         string
	SupplierID   *int64
	SupplierName *string
	Status       string
	TotalAmount  pgtype.Numeric
	VatAmount    pgtype.Numeric
	Note         *string
	LockVersion  int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Đọc lại PO (header) theo id — đường ĐỌC (GET detail) + readback sau ghi. Không
// thấy → ErrNoRows.
func (q *Queries) GetPurchaseOrderByID(ctx context.Context, id string) (GetPurchaseOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderByID, id)
	var i GetPurchaseOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SupplierID,
		&i.SupplierName,
		&i.Status,
		&i.TotalAmount,
		&i.VatAmount,
		&i.Note,
		&i.LockVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseOrderHeaderForUpdate = `-- name: GetPurchaseOrderHeaderForUpdate :one
SELECT id, code, supplier_id, supplier_name, status, total_amount, vat_amount,
       note, lock_version, created_at, updated_at
FROM app.purchase_orders
WHERE id = $1::uuid AND deleted_at IS NULL
FOR UPDATE
`

type GetPurchaseOrderHeaderForUpdateRow struct {
	ID           string
	Code         string
	SupplierID   *int64
	SupplierName *string
	Status       string
	TotalAmount  pgtype.Numeric
	VatAmount    pgtype.Numeric
	Note         *string
	LockVersion  int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Khoá dòng PO (FOR UPDATE) + trả header cho điều phối (confirm/receive/pay). Không
// thấy / đã xoá mềm → ErrNoRows.
func (q *Queries) GetPurchaseOrderHeaderForUpdate(ctx context.Context, id string) (GetPurchaseOrderHeaderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderHeaderForUpdate, id)
	var i GetPurchaseOrderHeaderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SupplierID,
		&i.SupplierName,
		&i.Status,
		&i.TotalAmount,
		&i.VatAmount,
		&i.Note,
		&i.LockVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPurchaseOrder = `-- name: InsertPurchaseOrder :one
INSERT INTO app.purchase_orders (
    id, code, supplier_id, supplier_name, status, total_amount, vat_amount, note
) VALUES (
    $1::uuid, $2::text, $3::bigint,
    $4::text, $5::text,
    $6::numeric, $7::numeric, $8::text
)
RETURNING id, code, supplier_id, supplier_name, status, total_amount, vat_amount,
          note, lock_version, created_at, updated_at
`

type InsertPurchaseOrderParams struct {
	ID           string
	Code         string
	SupplierID   *int64
	SupplierName *string
	Status       string
	TotalAmount  pgtype.Numeric
	VatAmount    pgtype.Numeric
	Note         *string
}

type InsertPurchaseOrderRow struct {
	ID           string
	Code         string
	SupplierID   *int64
	SupplierName *string
	Status       string
	TotalAmount  pgtype.Numeric
	VatAmount    pgtype.Numeric
	Note         *string
	LockVersion  int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Ghi header PO (status draft). id uuid v7 + code do app truyền. Trùng code (đua sinh
// mã, rất hiếm) → unique violation (ux_purchase_orders_code_alive) → app cấp số mới.
func (q *Queries) InsertPurchaseOrder(ctx context.Context, arg InsertPurchaseOrderParams) (InsertPurchaseOrderRow, error) {
	row := q.db.QueryRow(ctx, insertPurchaseOrder,
		arg.ID,
		arg.Code,
		arg.SupplierID,
		arg.SupplierName,
		arg.Status,
		arg.TotalAmount,
		arg.VatAmount,
		arg.Note,
	)
	var i InsertPurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.SupplierID,
		&i.SupplierName,
		&i.Status,
		&i.TotalAmount,
		&i.VatAmount,
		&i.Note,
		&i.LockVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPurchaseOrderIdemKey = `-- name: InsertPurchaseOrderIdemKey :exec
INSERT INTO app.purchase_order_idempotency (idem_key, po_id, po_code)
VALUES ($1::text, $2::uuid, $3::text)
ON CONFLICT (idem_key) DO NOTHING
`

type InsertPurchaseOrderIdemKeyParams struct {
	IdemKey string
	PoID    string
	PoCode  string
}

// Bind Idempotency-Key tạo PO → 1 PO. ON CONFLICT DO NOTHING; app đọc lại để biết
// thắng đua hay không (tái dùng pattern app.order_idempotency của orders).
func (q *Queries) InsertPurchaseOrderIdemKey(ctx context.Context, arg InsertPurchaseOrderIdemKeyParams) error {
	_, err := q.db.Exec(ctx, insertPurchaseOrderIdemKey, arg.IdemKey, arg.PoID, arg.PoCode)
	return err
}

const insertPurchaseOrderItem = `-- name: InsertPurchaseOrderItem :exec
INSERT INTO app.purchase_order_items (
    id, po_id, line_no, product_id, quantity, unit_cost, vat_rate,
    batch_code, expiry_date, manufacturing_date, line_total
) VALUES (
    $1::uuid, $2::uuid, $3::int, $4::bigint,
    $5::numeric, $6::numeric, $7::numeric,
    $8::text, $9::date,
    $10::date, $11::numeric
)
`

type InsertPurchaseOrderItemParams struct {
	ID                string
	PoID              string
	LineNo            int32
	ProductID         int64
	Quantity          pgtype.Numeric
	UnitCost          pgtype.Numeric
	VatRate           pgtype.Numeric
	BatchCode         *string
	ExpiryDate        pgtype.Date
	ManufacturingDate pgtype.Date
	LineTotal         pgtype.Numeric
}

// Ghi một dòng hàng PO. id uuid v7 do app truyền. line_no thứ tự dòng (UNIQUE po_id,line_no).
func (q *Queries) InsertPurchaseOrderItem(ctx context.Context, arg InsertPurchaseOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertPurchaseOrderItem,
		arg.ID,
		arg.PoID,
		arg.LineNo,
		arg.ProductID,
		arg.Quantity,
		arg.UnitCost,
		arg.VatRate,
		arg.BatchCode,
		arg.ExpiryDate,
		arg.ManufacturingDate,
		arg.LineTotal,
	)
	return err
}

const listPurchaseOrderLines = `-- name: ListPurchaseOrderLines :many
SELECT id, po_id, line_no, product_id, quantity, unit_cost, vat_rate,
       batch_code, expiry_date, manufacturing_date, line_total
FROM app.purchase_order_items
WHERE po_id = $1::uuid
ORDER BY line_no ASC
`

// Các dòng hàng của một PO (theo line_no) — product/qty/unit_cost/vat/lô để nhập kho
// + post sổ. Hết → slice rỗng.
func (q *Queries) ListPurchaseOrderLines(ctx context.Context, poID string) ([]AppPurchaseOrderItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderLines, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppPurchaseOrderItem
	for rows.Next() {
		var i AppPurchaseOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.LineNo,
			&i.ProductID,
			&i.Quantity,
			&i.UnitCost,
			&i.VatRate,
			&i.BatchCode,
			&i.ExpiryDate,
			&i.ManufacturingDate,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT id, code, supplier_id, supplier_name, status, total_amount, vat_amount,
       note, lock_version, created_at, updated_at
FROM app.purchase_orders
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::bigint IS NULL OR supplier_id = $2::bigint)
  AND (
        NOT $3::boolean
        OR (created_at, id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6::int
`

type ListPurchaseOrdersParams struct {
	Status         *string
	SupplierID     *int64
	HasCursor      bool
	AfterCreatedAt pgtype.Timestamptz
	AfterID        string
	RowLimit       int32
}

type ListPurchaseOrdersRow struct {
	ID           string
	Code         string
	SupplierID   *int64
	SupplierName *string
	Status       string
	TotalAmount  pgtype.Numeric
	VatAmount    pgtype.Numeric
	Note         *string
	LockVersion  int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Danh sách PO còn sống (keyset created_at DESC, id DESC). Lọc optional status +
// supplier_id. LIMIT phân trang.
func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.Status,
		arg.SupplierID,
		arg.HasCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseOrdersRow
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.SupplierID,
			&i.SupplierName,
			&i.Status,
			&i.TotalAmount,
			&i.VatAmount,
			&i.Note,
			&i.LockVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPurchaseOrderCodeSeq = `-- name: NextPurchaseOrderCodeSeq :one

SELECT nextval('app.purchase_order_code_seq')::bigint AS seq
`

// Purchasing (mục 54 — chiều MUA, đối xứng orders chiều BÁN). GHI/ĐỌC bảng MỚI ở
// schema app (purchase_orders + purchase_order_items, goose 00007). Tiền NUMERIC →
// common/money ở repo (KHÔNG float); quantity NUMERIC(20,4) → inventory/domain.Quantity
// (decimal); vat_rate NUMERIC(6,4) → shopspring/decimal. Mã PO app sinh từ
// app.purchase_order_code_seq + tiền tố. Đổi trạng thái dùng FOR UPDATE + guard
// status cũ (state machine THUẦN ở domain). Nhập kho/post sổ/chi NCC KHÔNG ở đây —
// purchasing/app gọi PORT inventory/accounting/finance với CÙNG tx (gộp atomic).
// Cấp số tăng dần cho mã PO (app ghép tiền tố + zero-pad). An toàn đua.
func (q *Queries) NextPurchaseOrderCodeSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextPurchaseOrderCodeSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updatePurchaseOrderStatus = `-- name: UpdatePurchaseOrderStatus :execrows
UPDATE app.purchase_orders
SET status = $1::text,
    lock_version = lock_version + 1,
    updated_at = now()
WHERE id = $2::uuid
  AND status = $3::text
  AND deleted_at IS NULL
`

type UpdatePurchaseOrderStatusParams struct {
	NewStatus      string
	ID             string
	ExpectedStatus string
}

// Đổi trạng thái PO (guard status cũ + bump lock_version). Trả số dòng đổi — 0 nghĩa
// là PO đã đổi trạng thái bởi luồng khác (service map Conflict).
func (q *Queries) UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePurchaseOrderStatus, arg.NewStatus, arg.ID, arg.ExpectedStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
