// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vat.sql

package appdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureSerial = `-- name: EnsureSerial :exec
INSERT INTO app.invoice_serials (serial, mau_so, next_no)
VALUES ($1::text, COALESCE($2::text, ''), 1)
ON CONFLICT (serial) DO NOTHING
`

type EnsureSerialParams struct {
	Serial string
	MauSo  *string
}

// Tạo dòng serial nếu chưa có (idempotent). next_no khởi 1. mau_so optional.
// Gọi trước NextInvoiceNo để đảm bảo dòng tồn tại cho FOR UPDATE.
func (q *Queries) EnsureSerial(ctx context.Context, arg EnsureSerialParams) error {
	_, err := q.db.Exec(ctx, ensureSerial, arg.Serial, arg.MauSo)
	return err
}

const findIssuedInvoiceByOrder = `-- name: FindIssuedInvoiceByOrder :one

SELECT id, order_code, customer_tax_code, serial, invoice_no, issue_date,
       subtotal, vat_amount, total, status, lock_version, created_at
FROM app.sales_invoices
WHERE order_code = $1::text
  AND status = 'issued'
`

// VAT (P5 — hoá đơn GTGT). GHI object MỚI ở schema app (sales_invoices/_lines/
// invoice_serials). Tiền = NUMERIC → common/money ở repo (KHÔNG float). PK uuid
// sinh app-side (common/id v7) và truyền vào INSERT. Phát hành HĐ chạy TRONG tx
// do caller (orders) truyền (gộp atomic với giao hàng): service cấp số gapless
// (FOR UPDATE serial) → insert header → insert từng line.
// Idempotency 1 đơn 1 HĐ: tìm HĐ đã 'issued' cho order_code. Có → service trả
// HĐ cũ (no-op, không phát hành trùng). Không thấy → pgx.ErrNoRows.
func (q *Queries) FindIssuedInvoiceByOrder(ctx context.Context, orderCode string) (AppSalesInvoice, error) {
	row := q.db.QueryRow(ctx, findIssuedInvoiceByOrder, orderCode)
	var i AppSalesInvoice
	err := row.Scan(
		&i.ID,
		&i.OrderCode,
		&i.CustomerTaxCode,
		&i.Serial,
		&i.InvoiceNo,
		&i.IssueDate,
		&i.Subtotal,
		&i.VatAmount,
		&i.Total,
		&i.Status,
		&i.LockVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getSalesInvoice = `-- name: GetSalesInvoice :one
SELECT id, order_code, customer_tax_code, serial, invoice_no, issue_date,
       subtotal, vat_amount, total, status, lock_version, created_at
FROM app.sales_invoices
WHERE id = $1::uuid
`

// Một HĐ theo id (cho HTTP đọc /v1/vat/invoices/{id}).
func (q *Queries) GetSalesInvoice(ctx context.Context, id string) (AppSalesInvoice, error) {
	row := q.db.QueryRow(ctx, getSalesInvoice, id)
	var i AppSalesInvoice
	err := row.Scan(
		&i.ID,
		&i.OrderCode,
		&i.CustomerTaxCode,
		&i.Serial,
		&i.InvoiceNo,
		&i.IssueDate,
		&i.Subtotal,
		&i.VatAmount,
		&i.Total,
		&i.Status,
		&i.LockVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertSalesInvoice = `-- name: InsertSalesInvoice :one
INSERT INTO app.sales_invoices (
    id, order_code, customer_tax_code, serial, invoice_no, issue_date,
    subtotal, vat_amount, total, status
) VALUES (
    $1::uuid, $2::text, $3::text, $4::text,
    $5::bigint, $6::date,
    $7::numeric, $8::numeric, $9::numeric, 'issued'
)
RETURNING id
`

type InsertSalesInvoiceParams struct {
	ID              string
	OrderCode       string
	CustomerTaxCode string
	Serial          string
	InvoiceNo       int64
	IssueDate       pgtype.Date
	Subtotal        pgtype.Numeric
	VatAmount       pgtype.Numeric
	Total           pgtype.Numeric
}

// Ghi header HĐ (status 'issued'). id sinh app-side. invoice_no đã cấp gapless.
// UNIQUE(serial,invoice_no) + unique index một phần (order_code WHERE issued)
// chặn trùng (race) → repo bắt 23505. RETURNING id để service insert lines.
func (q *Queries) InsertSalesInvoice(ctx context.Context, arg InsertSalesInvoiceParams) (string, error) {
	row := q.db.QueryRow(ctx, insertSalesInvoice,
		arg.ID,
		arg.OrderCode,
		arg.CustomerTaxCode,
		arg.Serial,
		arg.InvoiceNo,
		arg.IssueDate,
		arg.Subtotal,
		arg.VatAmount,
		arg.Total,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertSalesInvoiceLine = `-- name: InsertSalesInvoiceLine :exec
INSERT INTO app.sales_invoice_lines (
    id, invoice_id, line_no, product_id, description,
    quantity, unit_price, vat_rate, line_amount, line_vat
) VALUES (
    $1::uuid, $2::uuid, $3::int, $4::bigint, $5::text,
    $6::numeric, $7::numeric, $8::numeric,
    $9::numeric, $10::numeric
)
`

type InsertSalesInvoiceLineParams struct {
	ID          string
	InvoiceID   string
	LineNo      int32
	ProductID   int64
	Description string
	Quantity    pgtype.Numeric
	UnitPrice   pgtype.Numeric
	VatRate     pgtype.Numeric
	LineAmount  pgtype.Numeric
	LineVat     pgtype.Numeric
}

// Ghi một dòng HĐ (line_no theo thứ tự). Tiền NUMERIC; vat_rate là input. id
// sinh app-side. UNIQUE(invoice_id,line_no) chống trùng dòng.
func (q *Queries) InsertSalesInvoiceLine(ctx context.Context, arg InsertSalesInvoiceLineParams) error {
	_, err := q.db.Exec(ctx, insertSalesInvoiceLine,
		arg.ID,
		arg.InvoiceID,
		arg.LineNo,
		arg.ProductID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.VatRate,
		arg.LineAmount,
		arg.LineVat,
	)
	return err
}

const listSalesInvoiceLines = `-- name: ListSalesInvoiceLines :many
SELECT id, invoice_id, line_no, product_id, description,
       quantity, unit_price, vat_rate, line_amount, line_vat
FROM app.sales_invoice_lines
WHERE invoice_id = $1::uuid
ORDER BY line_no ASC, id ASC
`

// Các dòng của một HĐ, thứ tự theo line_no (ổn định).
func (q *Queries) ListSalesInvoiceLines(ctx context.Context, invoiceID string) ([]AppSalesInvoiceLine, error) {
	rows, err := q.db.Query(ctx, listSalesInvoiceLines, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSalesInvoiceLine
	for rows.Next() {
		var i AppSalesInvoiceLine
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.LineNo,
			&i.ProductID,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.VatRate,
			&i.LineAmount,
			&i.LineVat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesInvoices = `-- name: ListSalesInvoices :many
SELECT id, order_code, customer_tax_code, serial, invoice_no, issue_date,
       subtotal, vat_amount, total, status, lock_version, created_at
FROM app.sales_invoices
WHERE (
        $1::timestamptz IS NULL
        OR created_at < $1::timestamptz
        OR (created_at = $1::timestamptz
            AND id < $2::uuid)
      )
  AND ($3::text IS NULL OR order_code = $3::text)
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY created_at DESC, id DESC
LIMIT $5::int
`

type ListSalesInvoicesParams struct {
	AfterCreatedAt pgtype.Timestamptz
	AfterID        *string
	OrderCode      *string
	Status         *string
	RowLimit       int32
}

// Danh sách HĐ, keyset theo (created_at DESC, id DESC): trang kế lấy HĐ "cũ hơn"
// mốc cursor. @after_created_at NULL = trang đầu. Lọc optional order_code/status.
func (q *Queries) ListSalesInvoices(ctx context.Context, arg ListSalesInvoicesParams) ([]AppSalesInvoice, error) {
	rows, err := q.db.Query(ctx, listSalesInvoices,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.OrderCode,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSalesInvoice
	for rows.Next() {
		var i AppSalesInvoice
		if err := rows.Scan(
			&i.ID,
			&i.OrderCode,
			&i.CustomerTaxCode,
			&i.Serial,
			&i.InvoiceNo,
			&i.IssueDate,
			&i.Subtotal,
			&i.VatAmount,
			&i.Total,
			&i.Status,
			&i.LockVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInvoiceNo = `-- name: NextInvoiceNo :one
UPDATE app.invoice_serials
SET next_no = next_no + 1
WHERE serial = $1::text
RETURNING (next_no - 1)::bigint AS issued_no
`

// Cấp số HĐ GAPLESS theo serial: khoá dòng serial (FOR UPDATE — tuần tự hoá các
// tx cùng serial), lấy next_no hiện tại làm số HĐ, tăng next_no lên 1 NGAY trong
// CÙNG tx. Trả số vừa cấp. Phải gọi TRONG tx phát hành (cùng tx insert header)
// để gapless + atomic: nếu tx rollback thì next_no không bị tiêu hao.
// Dòng serial phải tồn tại trước (EnsureSerial) — không thì ErrNoRows.
func (q *Queries) NextInvoiceNo(ctx context.Context, serial string) (int64, error) {
	row := q.db.QueryRow(ctx, nextInvoiceNo, serial)
	var issued_no int64
	err := row.Scan(&issued_no)
	return issued_no, err
}
