-- SCHEMA THAM CHIẾU (strangler-fig, ADR 0001) — KHÔNG phải goose migration.
--
-- Mô tả bảng public.fund_accounts ĐANG TỒN TẠI (Postgres Supabase, monorepo
-- office.duoc.namviet) + TRIGGER cập nhật số dư quỹ, cho bounded context FINANCE
-- (P3 ghi phiếu thu). Mục đích: (1) sqlc type-check query finance ở compile-time
-- và (2) dbtest materialize bảng + trigger trong testcontainers (DB test trống).
-- TUYỆT ĐỐI KHÔNG chạy qua goose lên prod — backend chỉ ĐỌC/GHI bảng kế thừa,
-- không sở hữu DDL.
--
-- finance_transactions ĐÃ được khai ở db/schema/public_orders.sql (dùng chung lát
-- đọc orders + lát ghi finance) — KHÔNG khai lại ở đây.
--
-- Cột lấy nguyên văn từ office.duoc.namviet/namviet-infrastructure/supabase/
-- migrations/20260613080000_init_erp_schema.sql (CREATE TABLE fund_accounts) +
-- database_schema.md. Trigger handle_fund_balance_update lấy nguyên VĂN logic từ
-- nam_viet_erp/supabase/migrations/20260120000000_remote_schema.sql (đã grep prod).
-- PHẢI verify lại với prod thật (pg_dump/REST) khi có creds — prod hay lệch.
--
-- ========================================================================
-- ⚠️ DOUBLE-COUNT WARNING (đọc trước khi đụng số dư quỹ):
--   Bảng finance_transactions trên PROD có TRIGGER on_finance_transaction_change
--   AFTER INSERT/UPDATE/DELETE chạy handle_fund_balance_update() — TỰ cộng/trừ
--   fund_accounts.balance khi phiếu chuyển sang status='completed'. Do đó tầng Go
--   (RecordPaymentIn) chỉ INSERT phiếu với status='completed' và KHÔNG TỰ UPDATE
--   balance — nếu Go cũng cộng, số dư sẽ TĂNG GẤP ĐÔI. Trigger sở hữu số dư.
--   Schema test NÀY tái tạo trigger để integration test KHẲNG ĐỊNH điều đó.
-- ========================================================================

CREATE SCHEMA IF NOT EXISTS public;

-- Sổ quỹ tiền mặt / tài khoản ngân hàng. id = bigint IDENTITY (prod sinh id).
-- balance = NUMERIC (số dư realtime, do trigger duy trì). KHÔNG có lock_version
-- (migrate-later, ADR 0002).
CREATE TABLE IF NOT EXISTS public.fund_accounts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text NOT NULL,
    type            text NOT NULL,
    account_number  text,
    bank_id         bigint,
    initial_balance numeric NOT NULL DEFAULT 0,
    balance         numeric NOT NULL DEFAULT 0,    -- số dư realtime (trigger duy trì)
    currency        text DEFAULT 'VND',
    status          text NOT NULL DEFAULT 'active',
    account_id      text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    deleted_at      timestamptz
);

-- Hàm cập nhật số dư quỹ — TÁI TẠO logic prod (handle_fund_balance_update). CHỈ
-- cộng/trừ balance khi phiếu sang status='completed' (INSERT thẳng completed hoặc
-- UPDATE pending→completed). Hoàn/xoá phiếu completed → đảo lại. pending/approved
-- KHÔNG đổi số dư. Đặt Ở ĐÂY (cùng file fund_accounts) vì hàm dùng fund_accounts;
-- TRIGGER gắn hàm này vào finance_transactions nằm ở public_orders.sql (chạy SAU,
-- khi bảng finance_transactions đã tạo). Mục đích test: KHẲNG ĐỊNH RecordPaymentIn
-- (Go) chỉ INSERT phiếu completed và KHÔNG tự update balance → trigger cộng ĐÚNG
-- MỘT LẦN (không double-count).
CREATE OR REPLACE FUNCTION public.handle_fund_balance_update() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF (TG_OP = 'UPDATE' AND NEW.status = 'completed' AND OLD.status <> 'completed')
       OR (TG_OP = 'INSERT' AND NEW.status = 'completed') THEN
        IF NEW.flow = 'in' THEN
            UPDATE public.fund_accounts SET balance = balance + NEW.amount, updated_at = now() WHERE id = NEW.fund_account_id;
        ELSIF NEW.flow = 'out' THEN
            UPDATE public.fund_accounts SET balance = balance - NEW.amount, updated_at = now() WHERE id = NEW.fund_account_id;
        END IF;
    ELSIF (TG_OP = 'UPDATE' AND NEW.status = 'cancelled' AND OLD.status = 'completed') THEN
        IF OLD.flow = 'in' THEN
            UPDATE public.fund_accounts SET balance = balance - OLD.amount WHERE id = OLD.fund_account_id;
        ELSIF OLD.flow = 'out' THEN
            UPDATE public.fund_accounts SET balance = balance + OLD.amount WHERE id = OLD.fund_account_id;
        END IF;
    ELSIF (TG_OP = 'DELETE' AND OLD.status = 'completed') THEN
        IF OLD.flow = 'in' THEN
            UPDATE public.fund_accounts SET balance = balance - OLD.amount WHERE id = OLD.fund_account_id;
        ELSIF OLD.flow = 'out' THEN
            UPDATE public.fund_accounts SET balance = balance + OLD.amount WHERE id = OLD.fund_account_id;
        END IF;
    END IF;
    RETURN NULL;
END;
$$;
