-- SCHEMA THAM CHIẾU (strangler-fig, ADR 0001) — KHÔNG phải goose migration.
--
-- Mô tả các bảng public.* ĐANG TỒN TẠI (Postgres Supabase, nhánh monorepo
-- office.duoc.namviet) mà bounded context ORDERS cần ĐỌC THÊM ngoài public.orders.
-- Mục đích: (1) sqlc type-check query orders ở compile-time và (2) dbtest
-- materialize bảng + seed trong testcontainers (DB test trống). TUYỆT ĐỐI KHÔNG
-- chạy qua goose lên prod — backend chỉ ĐỌC các bảng kế thừa này, không sở hữu.
--
-- LƯU Ý QUAN TRỌNG VỀ public.orders (TÁI DÙNG, KHÔNG nhân bản — CLAUDE.md rule 12):
--   Bảng public.orders ĐÃ được khai (đầy đủ cột mà orders cần: code, customer_id,
--   creator_id, status, order_type, total_amount, final_amount, payment_status,
--   note, created_at, updated_at, deleted_at) ở db/schema/public_customers.sql —
--   nó dùng chung cho cả tính công nợ của customers. KHÔNG khai lại ở đây (sqlc +
--   Postgres CREATE TABLE trùng tên sẽ lỗi "table already exists"). File NÀY chỉ
--   THÊM hai bảng còn thiếu: order_items + finance_transactions.
--
-- Cột lấy nguyên văn từ office.duoc.namviet/database_schema.md +
-- namviet-backend-core/internal/features/finance_transactions/models.go.
-- PHẢI verify lại với prod thật (pg_dump/REST Object.keys) khi có creds.
--
-- GHI CHÚ NGHIỆP VỤ (đọc kỹ trước khi đụng "đã thu / còn nợ"):
--   * order_items.quantity là INTEGER (KHÔNG numeric) ở DB này. Map sang
--     domain.Quantity (decimal) ở repo để KHÔNG ép float + đồng nhất inventory.
--     unit_price/discount/total_line là numeric → common/money.
--   * "ĐÃ THU" của một đơn = tổng phiếu THU đã hoàn tất trỏ về đơn. Liên kết
--     finance_transactions → orders KHÔNG qua FK mà qua cặp:
--         ref_type = 'order'  AND  ref_id = orders.code   (ref_id là TEXT = MÃ
--         đơn, KHÔNG phải uuid id — xác nhận từ ERP B2BOrderDetailPage/
--         B2BOrderListPage set ref_id: order.code khi lập phiếu thu).
--     Chỉ tính giao dịch:  flow = 'in'  (lowercase ở ERP; ta so khớp
--     case-insensitive),  status = 'completed'  (tiền đã thực vào quỹ — auto
--     allocate fire ở mốc này),  deleted_at IS NULL,  và book_type IN
--     ('INTERNAL','BOTH')  → ĐÃ THU theo SỔ THỰC TẾ (loại phiếu chỉ-TAX để khỏi
--     tính trùng dòng tiền; giả định cần xác nhận với business).
--   * orders KHÔNG có cột paid_amount → "đã thu" luôn là SUY DIỄN read-only, KHÔNG
--     ghi ngược (ADR 0002 §B coi paid_amount là khoảng trống migrate-later).

CREATE SCHEMA IF NOT EXISTS public;

-- order_items: dòng hàng của một đơn. id = uuid, order_id = uuid (trỏ orders.id).
-- quantity là INTEGER ở DB này (không numeric).
CREATE TABLE IF NOT EXISTS public.order_items (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id          uuid NOT NULL,
    product_id        bigint NOT NULL,
    quantity          integer NOT NULL,
    uom               text NOT NULL,
    conversion_factor integer,
    base_quantity     integer,
    unit_price        numeric NOT NULL,         -- đơn giá bán (→ money)
    discount          numeric DEFAULT 0,        -- chiết khấu dòng (→ money)
    is_gift           boolean DEFAULT false,
    note              text,
    batch_no          text,
    expiry_date       date,
    total_line        numeric,                  -- thành tiền dòng (→ money)
    quantity_picked   integer DEFAULT 0,
    quantity_returned integer DEFAULT 0,
    created_at        timestamptz DEFAULT now(),
    deleted_at        timestamptz
);

-- finance_transactions: giao dịch thu/chi. id = bigint GENERATED BY DEFAULT AS
-- IDENTITY (prod sinh id — xác nhận từ migration init_erp_schema). Khai ĐỦ cột mà
-- HAI lát dùng chung: lát ĐỌC orders (suy diễn "đã thu") + lát GHI finance (P3 ghi
-- phiếu thu). amount = numeric (→ money). ref_id = TEXT (= mã đơn khi
-- ref_type='order'). book_type/flow/status là text tự do ở DB cũ (CHECK/enum là
-- việc migrate ADR 0002). bank_reference_id (mã webhook ngân hàng) dùng CHỐNG TRÙNG
-- phiếu thu tự động. business_type/created_by là cột thật của bảng (init_erp_schema)
-- — khai để INSERT của finance set đúng. KHÔNG khai cột HR/đối soát bank khác.
CREATE TABLE IF NOT EXISTS public.finance_transactions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            text NOT NULL,
    transaction_date timestamptz NOT NULL DEFAULT now(),
    flow            text NOT NULL,             -- 'in' | 'out'
    business_type   text NOT NULL DEFAULT 'other',
    amount          numeric NOT NULL,
    fund_account_id bigint NOT NULL,
    ref_type        text,                      -- 'order' khi trỏ về đơn bán
    ref_id          text,                      -- = orders.code khi ref_type='order'
    description     text,
    status          text NOT NULL DEFAULT 'pending', -- 'completed' = đã thực thu
    bank_reference_id text,                    -- mã tham chiếu webhook NH (chống trùng)
    book_type       text NOT NULL DEFAULT 'BOTH',    -- 'INTERNAL' | 'TAX' | 'BOTH'
    created_by      uuid,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    deleted_at      timestamptz
);

-- IDEMPOTENCY (migrate-later, ADR 0002 — prod CHƯA có 2 index này, cần verify +
-- thêm khi cutover): chống ghi phiếu thu TRÙNG ở tầng DB.
--   * code DUY NHẤT cho phiếu còn sống → phiếu thủ công sinh code idempotent từ
--     idem key; insert lần 2 cùng code → unique violation, app bắt và trả phiếu cũ.
--   * bank_reference_id DUY NHẤT (khi NOT NULL) → phiếu webhook chống trùng theo mã
--     giao dịch ngân hàng.
-- Partial WHERE deleted_at IS NULL: phiếu đã xoá mềm không chặn tạo lại.
CREATE UNIQUE INDEX IF NOT EXISTS ux_finance_transactions_code_alive
    ON public.finance_transactions (code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_finance_transactions_bankref_alive
    ON public.finance_transactions (bank_reference_id)
    WHERE bank_reference_id IS NOT NULL AND deleted_at IS NULL;

-- ⚠️ TRIGGER SỐ DƯ QUỸ (tái tạo prod on_finance_transaction_change) — đặt Ở ĐÂY
-- (không ở public_finance.sql) vì ApplyPublicSchema chạy file theo thứ tự TÊN:
-- public_finance.sql (tạo fund_accounts) TRƯỚC public_orders.sql (tạo
-- finance_transactions + trigger này). Hàm handle_fund_balance_update khai ở
-- public_finance.sql sau bảng fund_accounts. Trigger CHỈ cộng/trừ balance khi phiếu
-- sang status='completed'. Mục đích test: KHẲNG ĐỊNH RecordPaymentIn (Go) chỉ INSERT
-- phiếu completed và KHÔNG tự update balance → trigger cộng ĐÚNG MỘT LẦN (không
-- double-count). Trên PROD trigger đã tồn tại — Go tuyệt đối không UPDATE balance.
DROP TRIGGER IF EXISTS on_finance_transaction_change ON public.finance_transactions;
CREATE TRIGGER on_finance_transaction_change
    AFTER INSERT OR UPDATE OR DELETE ON public.finance_transactions
    FOR EACH ROW EXECUTE FUNCTION public.handle_fund_balance_update();

-- UNIQUE(code) trên public.orders (PROD: code TEXT NOT NULL UNIQUE — xác nhận từ
-- migration init 20260613080000_init_erp_schema.sql). public.orders KHAI ở
-- public_customers.sql (chạy TRƯỚC file này theo thứ tự tên alphabet) NHƯNG chưa
-- gắn UNIQUE — thêm ở ĐÂY (file của bounded context orders) để: (1) sqlc/DB test
-- khớp ràng buộc thật prod và (2) P4a có chốt chặn DB chống TẠO ĐƠN trùng mã (mã
-- do app sinh từ app.order_code_seq + tiền tố; race/lỗi sinh → unique violation
-- thay vì 2 đơn cùng mã). Partial WHERE deleted_at IS NULL: đơn xoá mềm không chặn
-- tái dùng mã (đồng nhất quy ước alive ở finance/vat).
CREATE UNIQUE INDEX IF NOT EXISTS ux_orders_code_alive
    ON public.orders (code) WHERE deleted_at IS NULL;
