-- ==========================================
-- 1. MODULE MARKETING (Quản lý Chiến dịch & Phân khúc)
-- ==========================================

-- Bảng Quản lý Chiến dịch Marketing (Giao dịch/Sự kiện -> UUID)
CREATE TABLE public.marketing_campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    objective TEXT NOT NULL CHECK (objective IN ('acquire_new', 'retention', 'boost_sales')),
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    budget NUMERIC DEFAULT 0,
    actual_cost NUMERIC DEFAULT 0,
    status TEXT NOT NULL CHECK (status IN ('draft', 'upcoming', 'running', 'completed', 'paused')) DEFAULT 'draft',
    target_segment_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL, -- Tạm map với customers hoặc bảng segments
    created_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
COMMENT ON TABLE public.marketing_campaigns IS 'Quản lý toàn diện các chiến dịch Marketing, Ngân sách và ROI';

-- ==========================================
-- 2. MODULE NHÂN SỰ & ĐÀO TẠO (HRM)
-- ==========================================

-- Bảng Khóa học & Đào tạo (Master Data -> BIGINT)
CREATE TABLE public.training_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content_type TEXT NOT NULL CHECK (content_type IN ('document', 'video', 'test')),
    content_url TEXT,
    passing_score INTEGER, -- Dành cho bài Test
    status TEXT NOT NULL CHECK (status IN ('active', 'inactive')) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
COMMENT ON TABLE public.training_courses IS 'Thư viện nội dung đào tạo nội bộ';

-- Bảng Chạy Lương (Payroll - Giao dịch Tài chính -> UUID)
CREATE TABLE public.payrolls (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    total_basic_salary NUMERIC DEFAULT 0,
    total_allowance NUMERIC DEFAULT 0,
    total_bonus_kpi NUMERIC DEFAULT 0,
    total_deduction NUMERIC DEFAULT 0,
    net_pay NUMERIC DEFAULT 0,
    status TEXT NOT NULL CHECK (status IN ('draft', 'pending_approval', 'approved', 'paid')) DEFAULT 'draft',
    created_by UUID REFERENCES public.users(id),
    approved_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.payrolls IS 'Quản lý các đợt chạy lương tổng của công ty';

-- Chi tiết lương từng nhân viên (Payroll Items)
CREATE TABLE public.payroll_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    payroll_id UUID NOT NULL REFERENCES public.payrolls(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES public.users(id),
    basic_salary NUMERIC NOT NULL DEFAULT 0,
    working_days NUMERIC NOT NULL DEFAULT 0,
    kpi_score NUMERIC DEFAULT 0,
    bonuses NUMERIC DEFAULT 0,
    deductions NUMERIC DEFAULT 0,
    net_pay NUMERIC NOT NULL DEFAULT 0,
    UNIQUE(payroll_id, employee_id)
);

-- ==========================================
-- 3. MODULE KẾ TOÁN CHUYÊN SÂU (ADVANCED ACCOUNTING)
-- ==========================================

ALTER TABLE public.chart_of_accounts ADD CONSTRAINT chart_of_accounts_account_code_key UNIQUE (account_code);

CREATE TABLE public.accounting_journals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entry_date DATE NOT NULL,
    doc_type TEXT NOT NULL, -- Ví dụ: Phiếu Thu, Phiếu Xuất Kho
    source_ref_id TEXT, -- Trỏ về ID của Phiếu thu/Đơn hàng
    description TEXT,
    account_debit TEXT NOT NULL REFERENCES public.chart_of_accounts(account_code), -- Tài khoản Nợ (VD: 111)
    account_credit TEXT NOT NULL REFERENCES public.chart_of_accounts(account_code), -- Tài khoản Có (VD: 511)
    amount NUMERIC NOT NULL CHECK (amount > 0),
    posted_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.accounting_journals IS 'Sổ nhật ký chung, hạch toán Nợ/Có. Nguồn dữ liệu sạch xuất ra MISA.';
