-- ==============================================================================
-- PHẦN 6: VẬN HÀNH MỞ RỘNG (TÀI SẢN, TÍCH HỢP, WEBHOOK)
-- ==============================================================================

-- 1. MODULE TÀI CHÍNH & SỔ QUỸ (Đã tạo ở Phase 1)

-- 2. MODULE QUẢN LÝ TÀI SẢN (ASSETS)
CREATE TABLE public.assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    purchase_price NUMERIC NOT NULL,
    purchase_date DATE NOT NULL,
    depreciation_months INTEGER NOT NULL, -- Số tháng khấu hao
    status TEXT NOT NULL CHECK (status IN ('active', 'maintenance', 'liquidated')) DEFAULT 'active',
    assigned_to UUID REFERENCES auth.users(id), -- Giao cho ai sử dụng
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Bảng lưu vết Webhook (Xử lý SePay, Shopee, GHTK)
CREATE TABLE public.webhook_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider TEXT NOT NULL, -- VD: 'sepay', 'shopee'
    payload JSONB NOT NULL, -- Dữ liệu gốc bắn về
    status TEXT NOT NULL CHECK (status IN ('success', 'failed', 'processing')) DEFAULT 'processing',
    error_message TEXT,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.webhook_logs IS 'Hộp đen lưu trữ toàn bộ Webhook từ bên thứ 3. Phục vụ đối soát và debug.';

-- 4. Cấu hình Đối tác thứ 3 (Lưu Token an toàn)
CREATE TABLE public.third_party_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL UNIQUE,
    access_token TEXT,
    refresh_token TEXT,
    config JSONB DEFAULT '{}'::jsonb, -- Cấu hình riêng (VD: Zalo OA ID)
    status TEXT DEFAULT 'connected',
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 5. MODULE CẤU HÌNH GIAO DIỆN (CMS/SETTINGS)
CREATE TABLE public.system_configs (
    key TEXT PRIMARY KEY, -- Ví dụ: 'retail_theme', 'b2b_popup_banner'
    value JSONB NOT NULL,
    description TEXT,
    updated_by UUID REFERENCES auth.users(id),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- PHẦN TỐI ƯU CỦA SẾP: HỌC MÁY ĐỒNG BỘ NHÀ CUNG CẤP (SUPPLIER MAPPING)
-- ==============================================================================

-- Bảng này đã được tinh chỉnh lại theo đúng luồng Kế toán Hóa đơn điện tử
CREATE TABLE public.vendor_product_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_tax_code TEXT NOT NULL, -- Lấy thẳng từ file XML Hóa đơn
    vendor_product_name TEXT NOT NULL, -- Tên thuốc ghi trên hóa đơn NCC
    vendor_unit TEXT, -- Đơn vị tính của NCC (VD: Hộp 10 vỉ)
    internal_product_id BIGINT NOT NULL REFERENCES public.products(id), -- Map về ID nội bộ
    internal_unit TEXT, -- Map về Đơn vị quy đổi nội bộ
    created_at TIMESTAMPTZ DEFAULT now(),
    last_used_at TIMESTAMPTZ DEFAULT now(),
    updated_by UUID REFERENCES auth.users(id),
    UNIQUE(vendor_tax_code, vendor_product_name) -- Chống map trùng
);
COMMENT ON TABLE public.vendor_product_mappings IS 'Từ điển AI: Tự động dịch tên sản phẩm của NCC sang tên nội bộ Nam Việt';

-- ==============================================================================
-- PHẦN 7: HỆ SINH THÁI TƯƠNG TÁC & TRỢ LÝ AI (AGENTIC WORKFLOW)
-- ==============================================================================

-- 6. Mạng xã hội nội bộ (Internal Chat)
CREATE TABLE public.internal_channels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT,
    type TEXT NOT NULL CHECK (type IN ('direct', 'group', 'department')),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.internal_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    channel_id UUID NOT NULL REFERENCES public.internal_channels(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES auth.users(id),
    content TEXT,
    attachments JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Trợ lý AI & Phân quyền Mạng xã hội (Cực kỳ quan trọng)
CREATE TABLE public.user_social_mappings (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id),
    telegram_id TEXT UNIQUE,
    zalo_id TEXT UNIQUE,
    is_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.user_social_mappings IS 'Định danh nhân sự qua mạng xã hội, đảm bảo chỉ người của công ty mới được gọi Bot';

CREATE TABLE public.agent_workflows (
    intent_code TEXT PRIMARY KEY, -- VD: 'CREATE_RECEIPT', 'APPROVE_EXPENSE'
    description TEXT NOT NULL,
    required_permission TEXT NOT NULL, -- Map thẳng vào Role_Permissions. Cốt lõi của việc Sếp phân quyền cho Kế toán/Phó GĐ!
    draft_only BOOLEAN DEFAULT true, -- TRUE: Chỉ tạo Nháp. FALSE: Chạy thẳng (Chỉ dành cho thao tác Read)
    api_endpoint TEXT NOT NULL, -- Endpoint nội bộ để Bot gọi tới
    is_active BOOLEAN DEFAULT true
);
COMMENT ON TABLE public.agent_workflows IS 'Định nghĩa các tập lệnh AI được phép thực thi và quyền hạn đi kèm';

-- 8. Quy trình Phê duyệt Động (Dynamic Approvals)
CREATE TABLE public.approval_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    requester_id UUID NOT NULL REFERENCES auth.users(id),
    module TEXT NOT NULL, -- VD: 'FINANCE_PAYMENT', 'ASSET_PURCHASE'
    reference_id TEXT, -- ID của phiếu chi/đơn hàng tương ứng
    payload JSONB NOT NULL, -- Chứa toàn bộ Data cần duyệt (để render UI)
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    current_step INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.approval_steps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    request_id UUID NOT NULL REFERENCES public.approval_requests(id) ON DELETE CASCADE,
    step_order INTEGER NOT NULL,
    approver_id UUID REFERENCES auth.users(id), -- Trống nếu duyệt theo Role
    approver_role_id UUID REFERENCES public.roles(id), -- Duyệt theo chức danh (VD: Cứ Trưởng phòng là duyệt được)
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    note TEXT,
    processed_at TIMESTAMPTZ
);

-- 9. MODULE PROMOTION ENGINE (ĐỘNG CƠ KHUYẾN MÃI)
CREATE TABLE public.promotions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    rules JSONB NOT NULL, -- Rất quan trọng: {"min_order": 500000, "discount_percent": 10, "max_discount": 50000}
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.customer_vouchers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    promotion_id UUID REFERENCES public.promotions(id),
    customer_id BIGINT REFERENCES public.customers(id),
    is_used BOOLEAN DEFAULT false,
    used_at TIMESTAMPTZ,
    order_id UUID -- Trỏ về đơn hàng đã dùng
);
