-- ==========================================
-- 1. MODULE INVENTORY (Lõi Quản trị Tồn kho)
-- ==========================================

-- Bảng Quản lý Lô Hàng (Master Data của Kho)
CREATE TABLE public.batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    batch_code TEXT NOT NULL,
    expiry_date DATE NOT NULL,
    manufacturing_date DATE,
    inbound_price NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    UNIQUE(product_id, batch_code)
);
COMMENT ON TABLE public.batches IS 'Quản lý thông tin Lô và Hạn sử dụng của sản phẩm';
COMMENT ON COLUMN public.batches.inbound_price IS 'Giá vốn nhập kho tại thời điểm tạo lô';

-- Bảng Tồn kho theo Lô (Mapping thực tế tại kho)
CREATE TABLE public.inventory_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES public.warehouses(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    batch_id BIGINT NOT NULL REFERENCES public.batches(id) ON DELETE CASCADE,
    quantity NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(warehouse_id, product_id, batch_id)
);
COMMENT ON TABLE public.inventory_batches IS 'Lưu trữ số lượng tồn kho chi tiết đến từng Lô tại từng Kho';

-- Bảng Sổ Cái Tồn Kho (Inventory Transactions - Trái tim của việc truy vết)
CREATE TABLE public.inventory_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    warehouse_id BIGINT NOT NULL REFERENCES public.warehouses(id),
    product_id BIGINT NOT NULL REFERENCES public.products(id),
    batch_id BIGINT REFERENCES public.batches(id),
    type TEXT NOT NULL CHECK (type IN ('inbound', 'outbound', 'transfer', 'adjustment', 'return')),
    action_group TEXT, -- Dùng để nhóm các giao dịch (VD: SALE, PURCHASE_RECEIPT)
    quantity NUMERIC NOT NULL, -- Số dương là nhập, số âm là xuất
    unit_price NUMERIC DEFAULT 0,
    ref_id TEXT, -- Trỏ đến mã Đơn hàng / Phiếu nhập / Phiếu chuyển
    description TEXT,
    partner_id BIGINT REFERENCES public.customers(id), -- B2B hoặc B2C
    created_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.inventory_transactions IS 'Sổ cái ghi nhận mọi biến động tăng/giảm của kho hàng (Bất biến, không update/delete)';

-- ==========================================
-- 2. MODULE CLINICAL (Nghiệp vụ Y tế)
-- ==========================================

-- Bảng Lịch hẹn (Appointments)
CREATE TABLE public.appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id BIGINT NOT NULL REFERENCES public.customers(id),
    doctor_id UUID REFERENCES public.users(id),
    room_id BIGINT REFERENCES public.warehouses(id), -- Bản chất phòng khám là 1 kho/cơ sở
    service_type TEXT NOT NULL CHECK (service_type IN ('examination', 'vaccination', 'procedure')),
    appointment_time TIMESTAMPTZ NOT NULL,
    check_in_time TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('pending', 'confirmed', 'checked_in', 'waiting', 'examining', 'completed', 'cancelled', 'observing')) DEFAULT 'pending',
    symptoms JSONB DEFAULT '[]'::jsonb,
    note TEXT,
    created_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
COMMENT ON TABLE public.appointments IS 'Quản lý lịch hẹn khám bệnh và tiêm chủng của khách hàng';

-- Bảng Hồ sơ Khám bệnh (Medical Visits)
CREATE TABLE public.medical_visits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    appointment_id UUID UNIQUE REFERENCES public.appointments(id),
    customer_id BIGINT NOT NULL REFERENCES public.customers(id),
    doctor_id UUID REFERENCES public.users(id),
    
    -- Chỉ số sinh tồn (Vital Signs)
    temperature NUMERIC,
    pulse INTEGER,
    sp02 INTEGER,
    bp_systolic INTEGER,
    bp_diastolic INTEGER,
    weight NUMERIC,
    height NUMERIC,
    
    -- Chẩn đoán lâm sàng
    symptoms TEXT,
    examination_summary TEXT,
    diagnosis TEXT,
    icd_code TEXT,
    doctor_notes TEXT,
    red_flags JSONB DEFAULT '[]'::jsonb, -- Cảnh báo AI hoặc Bác sĩ
    
    status TEXT NOT NULL CHECK (status IN ('in_progress', 'ready_for_vaccine', 'ready_for_procedure', 'finished')) DEFAULT 'in_progress',
    created_by UUID REFERENCES public.users(id),
    updated_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
COMMENT ON TABLE public.medical_visits IS 'Hồ sơ bệnh án điện tử (EMR) cho mỗi lần thăm khám';

-- Sổ Tiêm chủng (Vaccination Records)
CREATE TABLE public.customer_vaccination_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id BIGINT NOT NULL REFERENCES public.customers(id),
    appointment_id UUID REFERENCES public.appointments(id),
    product_id BIGINT NOT NULL REFERENCES public.products(id), -- Liên kết đến Vắc-xin
    dose_number INTEGER NOT NULL DEFAULT 1,
    expected_date DATE NOT NULL,
    actual_date DATE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'cancelled', 'delayed')) DEFAULT 'pending',
    consulted_by UUID REFERENCES public.users(id),
    administered_by UUID REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- ==========================================
-- 3. MODULE AI CHAT (Hệ thống Trợ lý)
-- ==========================================

CREATE TABLE public.chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id),
    platform TEXT NOT NULL CHECK (platform IN ('web', 'app', 'zalo')) DEFAULT 'web',
    status TEXT NOT NULL CHECK (status IN ('bot', 'human_handoff', 'closed')) DEFAULT 'bot',
    context JSONB NOT NULL DEFAULT '{}'::jsonb, -- Lưu ngữ cảnh giỏ hàng, đơn đang xem...
    assigned_sales_id UUID REFERENCES public.users(id),
    started_at TIMESTAMPTZ DEFAULT now(),
    last_activity_at TIMESTAMPTZ DEFAULT now(),
    closed_at TIMESTAMPTZ
);

CREATE TABLE public.chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT,
    intent TEXT, -- AI phân loại Intent (Ví dụ: order_inquiry, medical_advice)
    entities JSONB, -- Các thực thể AI bóc tách được
    llm_meta JSONB, -- Token usage, latency...
    created_at TIMESTAMPTZ DEFAULT now()
);
