-- ==============================================================================
-- BỔ SUNG MODULE 5.7: QUẢN LÝ CA KÍP & LỊCH TRỰC
-- ==============================================================================

-- 1. Bảng Khai báo Khung Giờ Ca Trực (Shifts)
CREATE TABLE public.work_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES public.warehouses(id), -- Áp dụng cho chi nhánh nào
    name TEXT NOT NULL, -- VD: 'Ca Sáng', 'Ca Chiều', 'Ca Hành Chính'
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Bảng Đăng ký & Gán Ca (Shift Assignments) - Nơi xử lý trống ca/bù ca
CREATE TABLE public.shift_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id BIGINT NOT NULL REFERENCES public.work_shifts(id),
    user_id UUID NOT NULL REFERENCES auth.users(id),
    work_date DATE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('scheduled', 'attended', 'absent', 'leave')) DEFAULT 'scheduled',
    is_overtime BOOLEAN DEFAULT false, -- Đánh dấu ca làm thêm để nhân HR nhân hệ số lương
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id, work_date, shift_id) -- Chống đăng ký trùng
);
COMMENT ON TABLE public.shift_assignments IS 'Bảng lịch trực realtime. Biết ngay ai trực ngày nào, ca nào bị trống.';

-- 3. Bảng Chốt Tiền Cuối Ca (Shift Handovers) - Giải quyết yêu cầu B của Sếp
CREATE TABLE public.shift_handovers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id BIGINT REFERENCES public.shift_assignments(id),
    user_id UUID NOT NULL REFERENCES auth.users(id),
    branch_id BIGINT NOT NULL REFERENCES public.warehouses(id),
    
    -- Dữ liệu do Hệ thống tính toán tự động
    system_cash_amount NUMERIC NOT NULL DEFAULT 0, -- Tổng tiền mặt thu được trong ca
    system_cod_amount NUMERIC NOT NULL DEFAULT 0, -- Tổng tiền COD cần theo dõi
    
    -- Dữ liệu do Nhân viên thực nộp
    actual_cash_submitted NUMERIC NOT NULL, 
    
    status TEXT NOT NULL CHECK (status IN ('pending_finance', 'verified')) DEFAULT 'pending_finance',
    finance_transaction_id BIGINT REFERENCES public.finance_transactions(id), -- Trỏ về phiếu thu nội bộ sau khi Kế toán xác nhận
    
    created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.shift_handovers IS 'Biên bản nộp tiền khi hết ca. Nhân viên nhập số tiền thực tế, hệ thống tạo Phiếu Thu chờ Kế toán duyệt.';
