-- ==========================================
-- 1. MASTER DATA & SYSTEM (Dữ liệu nền tảng)
-- ==========================================

CREATE TABLE public.companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tax_code TEXT NOT NULL,
    name TEXT NOT NULL,
    short_name TEXT,
    address TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    logo_url TEXT,
    representative_name TEXT NOT NULL,
    business_license_url TEXT[],
    mission TEXT,
    vision TEXT,
    status TEXT CHECK (status IN ('active', 'inactive')) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- BẢNG CATEGORIES (Đã fix lỗi BIGINT parent_id)
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'hidden')) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ -- Soft Delete
);

CREATE TABLE public.manufacturers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    country TEXT,
    logo_url TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- ==========================================
-- 2. USERS & AUTHENTICATION
-- ==========================================

CREATE TABLE public.users (
    id UUID PRIMARY KEY, -- Giữ nguyên UUID để map với auth.users của Supabase
    email TEXT,
    full_name TEXT,
    avatar_url TEXT,
    employee_code TEXT,
    position TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending_approval', 'active', 'inactive')) DEFAULT 'pending_approval',
    dob DATE,
    phone TEXT,
    gender TEXT,
    cccd TEXT,
    cccd_issue_date DATE,
    address TEXT,
    marital_status TEXT,
    cccd_front_url TEXT,
    cccd_back_url TEXT,
    education_level TEXT,
    specialization TEXT,
    bank_name TEXT,
    bank_account_number TEXT,
    bank_account_name TEXT,
    hobbies TEXT,
    limitations TEXT,
    strengths TEXT,
    needs TEXT,
    work_state TEXT DEFAULT 'working',
    role_id UUID REFERENCES public.roles(id) ON DELETE SET NULL,
    company_id UUID REFERENCES public.companies(id) ON DELETE SET NULL,
    warehouse_id BIGINT, -- FK update later
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    profile_updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

-- ==========================================
-- 3. CRM & B2B/B2C CUSTOMERS
-- ==========================================

-- BẢNG KHÁCH HÀNG (ĐÃ GỘP B2C & B2B - Thiết kế linh hoạt với JSONB)
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code TEXT UNIQUE,
    name TEXT NOT NULL,
    customer_type TEXT NOT NULL CHECK (customer_type IN ('B2C', 'B2B')) DEFAULT 'B2C',
    phone TEXT,
    email TEXT,
    address TEXT,
    status TEXT NOT NULL CHECK (status IN ('active', 'inactive', 'banned')) DEFAULT 'active',
    
    -- Thông tin cá nhân (B2C chủ yếu dùng)
    dob DATE,
    gender TEXT CHECK (gender IN ('male', 'female', 'other')),
    cccd TEXT,
    loyalty_points INTEGER DEFAULT 0,
    
    -- Thông tin Doanh nghiệp (B2B metadata)
    b2b_metadata JSONB DEFAULT '{}'::jsonb, 
    -- Sẽ chứa: tax_code, debt_limit, payment_term, business_license_url...
    
    current_debt NUMERIC DEFAULT 0,
    updated_by UUID REFERENCES public.users(id), -- Map với bảng users
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ -- Soft Delete
);

-- Tối ưu hóa truy vấn JSONB cho B2B
CREATE INDEX idx_customers_b2b_metadata ON public.customers USING GIN (b2b_metadata);

-- ==========================================
-- 4. PRODUCTS & INVENTORY
-- ==========================================

CREATE TABLE public.warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    name TEXT NOT NULL,
    unit TEXT NOT NULL DEFAULT 'Hộp',
    address TEXT,
    type TEXT NOT NULL DEFAULT 'retail',
    latitude NUMERIC,
    longitude NUMERIC,
    code TEXT,
    manager TEXT,
    phone TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
    outlet_type TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- Bổ sung FK cho users -> warehouses sau khi bảng warehouses đã có
ALTER TABLE public.users ADD CONSTRAINT fk_users_warehouse FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;

CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sku TEXT,
    barcode TEXT,
    description TEXT,
    active_ingredient TEXT,
    image_url TEXT,
    status TEXT NOT NULL CHECK (status IN ('active', 'inactive')) DEFAULT 'active',
    fts TSVECTOR,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    manufacturer_id BIGINT REFERENCES public.manufacturers(id) ON DELETE SET NULL,
    category_name TEXT,
    manufacturer_name TEXT,
    distributor_id BIGINT,
    invoice_price NUMERIC DEFAULT 0,
    actual_cost NUMERIC NOT NULL DEFAULT 0,
    wholesale_unit TEXT DEFAULT 'Hộp',
    retail_unit TEXT DEFAULT 'Vỉ',
    conversion_factor INTEGER DEFAULT 1,
    wholesale_margin_value NUMERIC DEFAULT 0,
    wholesale_margin_type TEXT DEFAULT '%',
    retail_margin_value NUMERIC DEFAULT 0,
    retail_margin_type TEXT DEFAULT '%',
    items_per_carton INTEGER DEFAULT 1,
    carton_weight NUMERIC DEFAULT 0,
    carton_dimensions TEXT,
    purchasing_policy TEXT DEFAULT 'ALLOW_LOOSE',
    registration_number TEXT,
    packing_spec TEXT,
    stock_management_type TEXT DEFAULT 'lot_date',
    wholesale_margin_rate NUMERIC DEFAULT 0,
    retail_margin_rate NUMERIC DEFAULT 0,
    usage_instructions JSONB DEFAULT '{}'::jsonb,
    stock_status TEXT DEFAULT 'in_stock',
    product_images TEXT[] DEFAULT '{}'::text[],
    updated_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.product_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    unit_name TEXT NOT NULL,
    conversion_rate INTEGER DEFAULT 1,
    barcode TEXT,
    is_base BOOLEAN DEFAULT false,
    is_direct_sale BOOLEAN DEFAULT true,
    price_cost NUMERIC DEFAULT 0,
    price_sell NUMERIC DEFAULT 0,
    unit_type TEXT DEFAULT 'retail',
    price NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.product_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    warehouse_id BIGINT REFERENCES public.warehouses(id) ON DELETE CASCADE,
    stock_quantity NUMERIC NOT NULL DEFAULT 0,
    min_stock INTEGER DEFAULT 0,
    max_stock INTEGER DEFAULT 0,
    shelf_location TEXT DEFAULT 'Chưa xếp',
    location_cabinet TEXT,
    location_row TEXT,
    location_slot TEXT,
    updated_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==========================================
-- 5. ORDERS & SALES
-- ==========================================

-- BẢNG ORDERS (Đã dọn dẹp, chỉ còn 1 Customer ID)
CREATE TABLE public.orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- Giao dịch dùng UUID
    code TEXT NOT NULL UNIQUE,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE RESTRICT,
    creator_id UUID REFERENCES public.users(id),
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'SHIPPING', 'COMPLETED', 'CANCELLED', 'REFUNDED')) DEFAULT 'PENDING',
    order_type TEXT NOT NULL CHECK (order_type IN ('B2B', 'B2C')) DEFAULT 'B2C',
    total_amount NUMERIC DEFAULT 0,
    final_amount NUMERIC DEFAULT 0,
    payment_status TEXT CHECK (payment_status IN ('unpaid', 'partial', 'paid')) DEFAULT 'unpaid',
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ -- Soft Delete
);

CREATE TABLE public.order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    uom TEXT NOT NULL,
    conversion_factor INTEGER,
    base_quantity INTEGER,
    unit_price NUMERIC NOT NULL,
    discount NUMERIC DEFAULT 0,
    is_gift BOOLEAN DEFAULT false,
    note TEXT,
    batch_no TEXT,
    expiry_date DATE,
    total_line NUMERIC,
    quantity_picked INTEGER DEFAULT 0,
    quantity_returned INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- ==========================================
-- 6. FINANCE & ACCOUNTING
-- ==========================================

CREATE TABLE public.chart_of_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_code TEXT NOT NULL,
    name TEXT NOT NULL,
    parent_id UUID REFERENCES public.chart_of_accounts(id) ON DELETE SET NULL,
    type TEXT NOT NULL,
    balance_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    allow_posting BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.fund_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    location TEXT,
    account_number TEXT,
    bank_id BIGINT,
    initial_balance NUMERIC NOT NULL DEFAULT 0,
    balance NUMERIC NOT NULL DEFAULT 0,
    currency TEXT DEFAULT 'VND',
    status TEXT NOT NULL DEFAULT 'active',
    bank_info JSONB,
    description TEXT,
    account_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE public.finance_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    flow TEXT NOT NULL,
    business_type TEXT NOT NULL DEFAULT 'other',
    category_id BIGINT,
    amount NUMERIC NOT NULL,
    fund_account_id BIGINT NOT NULL REFERENCES public.fund_accounts(id),
    partner_type TEXT,
    partner_id TEXT,
    partner_name_cache TEXT,
    ref_type TEXT,
    ref_id TEXT,
    description TEXT,
    evidence_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    cash_tally JSONB,
    ref_advance_id BIGINT,
    target_bank_info JSONB,
    bank_reference_id TEXT,
    book_type TEXT NOT NULL DEFAULT 'BOTH',
    is_posted BOOLEAN NOT NULL DEFAULT false,
    created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
